site_name: GNS3 API Utility
site_description: A powerful command-line utility for managing GNS3v3 servers
site_author: Stefan Kuhl
site_url: https://stefanistkuhl.github.io/gns3-api-util/

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quick-start.md
  - Features:
      - Educational Workflows: features/educational-workflows.md
      - Remote Operations: features/remote-operations.md
      - Cluster Management: features/cluster-management.md
      - Sharing and Collaboration: features/sharing-and-collaboration.md
  - CLI Reference:
      - Commands: cli-reference/commands.md
  - Scripts:
      - Overview: scripts/overview.md
      - Walkthrough: scripts/walkthrough.md
      - Examples: scripts/examples.md
  - Automation:
      - Walkthrough: automation/walkthrough.md
  - Roadmap: roadmap.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.arithmatex
  - pymdownx.emoji
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          # format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

plugins:
  - search
