// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deletes.sql

package sqlc

import (
	"context"
)

const deleteClass = `-- name: DeleteClass :exec
DELETE FROM
    classes
WHERE
    class_id = ?
`

func (q *Queries) DeleteClass(ctx context.Context, classID int64) error {
	_, err := q.db.ExecContext(ctx, deleteClass, classID)
	return err
}

const deleteCluster = `-- name: DeleteCluster :exec
DELETE FROM
    clusters
WHERE
    cluster_id = ?
`

func (q *Queries) DeleteCluster(ctx context.Context, clusterID int64) error {
	_, err := q.db.ExecContext(ctx, deleteCluster, clusterID)
	return err
}

const deleteExerciseByName = `-- name: DeleteExerciseByName :exec
DELETE FROM
    exercises
WHERE
    name = ?
`

func (q *Queries) DeleteExerciseByName(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteExerciseByName, name)
	return err
}

const deleteExerciseForClass = `-- name: DeleteExerciseForClass :exec
DELETE FROM
    exercises
WHERE
    group_id IN (
        SELECT
            group_id
        FROM
            groups
        WHERE
            class_id IN (
                SELECT
                    class_id
                FROM
                    classes
                WHERE
                    classes.name = ?
            )
    )
`

func (q *Queries) DeleteExerciseForClass(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteExerciseForClass, name)
	return err
}

const deleteExerciseForClassOnNode = `-- name: DeleteExerciseForClassOnNode :exec
DELETE FROM
    exercises
WHERE
    group_id IN (
        SELECT
            g.group_id
        FROM
            groups g
        WHERE
            g.class_id IN (
                SELECT
                    class_id
                FROM
                    classes
                WHERE
                    classes.name = ?
            )
            AND g.group_id IN (
                SELECT
                    group_id
                FROM
                    group_assignments
                WHERE
                    node_id = ?
            )
    )
`

type DeleteExerciseForClassOnNodeParams struct {
	Name   string `json:"name"`
	NodeID int64  `json:"node_id"`
}

func (q *Queries) DeleteExerciseForClassOnNode(ctx context.Context, arg DeleteExerciseForClassOnNodeParams) error {
	_, err := q.db.ExecContext(ctx, deleteExerciseForClassOnNode, arg.Name, arg.NodeID)
	return err
}

const deleteExerciseRecord = `-- name: DeleteExerciseRecord :exec
DELETE FROM
    exercises
WHERE
    project_uuid = ?
`

func (q *Queries) DeleteExerciseRecord(ctx context.Context, projectUuid string) error {
	_, err := q.db.ExecContext(ctx, deleteExerciseRecord, projectUuid)
	return err
}

const deleteExerciseScoped = `-- name: DeleteExerciseScoped :exec
DELETE FROM
    exercises
WHERE
    exercises.name = ?
    AND group_id IN (
        SELECT
            group_id
        FROM
            groups
        WHERE
            class_id IN (
                SELECT
                    class_id
                FROM
                    classes
                WHERE
                    classes.name = ?
            )
    )
`

type DeleteExerciseScopedParams struct {
	Name   string `json:"name"`
	Name_2 string `json:"name_2"`
}

func (q *Queries) DeleteExerciseScoped(ctx context.Context, arg DeleteExerciseScopedParams) error {
	_, err := q.db.ExecContext(ctx, deleteExerciseScoped, arg.Name, arg.Name_2)
	return err
}

const deleteNode = `-- name: DeleteNode :exec
DELETE FROM
    nodes
WHERE
    node_id = ?
`

func (q *Queries) DeleteNode(ctx context.Context, nodeID int64) error {
	_, err := q.db.ExecContext(ctx, deleteNode, nodeID)
	return err
}

const nukeEverything = `-- name: NukeEverything :exec
DELETE FROM
    clusters
`

func (q *Queries) NukeEverything(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, nukeEverything)
	return err
}

const unassignGroupFromNode = `-- name: UnassignGroupFromNode :exec
DELETE FROM
    group_assignments
WHERE
    node_id = ?
    AND group_id = ?
`

type UnassignGroupFromNodeParams struct {
	NodeID  int64 `json:"node_id"`
	GroupID int64 `json:"group_id"`
}

func (q *Queries) UnassignGroupFromNode(ctx context.Context, arg UnassignGroupFromNodeParams) error {
	_, err := q.db.ExecContext(ctx, unassignGroupFromNode, arg.NodeID, arg.GroupID)
	return err
}
