// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inserts.sql

package sqlc

import (
	"context"
	"database/sql"
)

const assignGroupToNode = `-- name: AssignGroupToNode :exec
INSERT INTO
    group_assignments (node_id, group_id)
VALUES
    (?, ?)
`

type AssignGroupToNodeParams struct {
	NodeID  int64 `json:"node_id"`
	GroupID int64 `json:"group_id"`
}

func (q *Queries) AssignGroupToNode(ctx context.Context, arg AssignGroupToNodeParams) error {
	_, err := q.db.ExecContext(ctx, assignGroupToNode, arg.NodeID, arg.GroupID)
	return err
}

const createClass = `-- name: CreateClass :exec
INSERT INTO
    classes (cluster_id, name, description)
VALUES
    (?, ?, ?)
`

type CreateClassParams struct {
	ClusterID   int64          `json:"cluster_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateClass(ctx context.Context, arg CreateClassParams) error {
	_, err := q.db.ExecContext(ctx, createClass, arg.ClusterID, arg.Name, arg.Description)
	return err
}

const createClassReturning = `-- name: CreateClassReturning :one
INSERT INTO
    classes (cluster_id, name, description)
VALUES
    (?, ?, ?)
RETURNING
    class_id
`

type CreateClassReturningParams struct {
	ClusterID   int64          `json:"cluster_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateClassReturning(ctx context.Context, arg CreateClassReturningParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createClassReturning, arg.ClusterID, arg.Name, arg.Description)
	var class_id int64
	err := row.Scan(&class_id)
	return class_id, err
}

const createCluster = `-- name: CreateCluster :one
INSERT INTO
    clusters (name, description)
VALUES
    (?, ?)
RETURNING
    cluster_id,
    name,
    description
`

type CreateClusterParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateCluster(ctx context.Context, arg CreateClusterParams) (Cluster, error) {
	row := q.db.QueryRowContext(ctx, createCluster, arg.Name, arg.Description)
	var i Cluster
	err := row.Scan(&i.ClusterID, &i.Name, &i.Description)
	return i, err
}

const createGroup = `-- name: CreateGroup :exec
INSERT INTO
    groups (class_id, name)
VALUES
    (?, ?)
`

type CreateGroupParams struct {
	ClassID int64  `json:"class_id"`
	Name    string `json:"name"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) error {
	_, err := q.db.ExecContext(ctx, createGroup, arg.ClassID, arg.Name)
	return err
}

const createGroupReturning = `-- name: CreateGroupReturning :one
INSERT INTO
    groups (class_id, name)
VALUES
    (?, ?)
RETURNING
    group_id
`

type CreateGroupReturningParams struct {
	ClassID int64  `json:"class_id"`
	Name    string `json:"name"`
}

func (q *Queries) CreateGroupReturning(ctx context.Context, arg CreateGroupReturningParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createGroupReturning, arg.ClassID, arg.Name)
	var group_id int64
	err := row.Scan(&group_id)
	return group_id, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO
    users (group_id, username, full_name, default_password)
VALUES
    (?, ?, ?, ?)
`

type CreateUserParams struct {
	GroupID         int64          `json:"group_id"`
	Username        string         `json:"username"`
	FullName        sql.NullString `json:"full_name"`
	DefaultPassword string         `json:"default_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.GroupID,
		arg.Username,
		arg.FullName,
		arg.DefaultPassword,
	)
	return err
}

const createUserReturning = `-- name: CreateUserReturning :one
INSERT INTO
    users (group_id, username, full_name, default_password)
VALUES
    (?, ?, ?, ?)
RETURNING
    user_id
`

type CreateUserReturningParams struct {
	GroupID         int64          `json:"group_id"`
	Username        string         `json:"username"`
	FullName        sql.NullString `json:"full_name"`
	DefaultPassword string         `json:"default_password"`
}

func (q *Queries) CreateUserReturning(ctx context.Context, arg CreateUserReturningParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUserReturning,
		arg.GroupID,
		arg.Username,
		arg.FullName,
		arg.DefaultPassword,
	)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const insertExerciseRecord = `-- name: InsertExerciseRecord :exec
INSERT INTO
    exercises (project_uuid, group_id, name, state)
VALUES
    (?, ?, ?, ?)
`

type InsertExerciseRecordParams struct {
	ProjectUuid string         `json:"project_uuid"`
	GroupID     int64          `json:"group_id"`
	Name        string         `json:"name"`
	State       sql.NullString `json:"state"`
}

func (q *Queries) InsertExerciseRecord(ctx context.Context, arg InsertExerciseRecordParams) error {
	_, err := q.db.ExecContext(ctx, insertExerciseRecord,
		arg.ProjectUuid,
		arg.GroupID,
		arg.Name,
		arg.State,
	)
	return err
}

const insertNode = `-- name: InsertNode :exec
INSERT INTO
    nodes (
        cluster_id,
        protocol,
        host,
        port,
        weight,
        max_groups,
        auth_user
    )
VALUES
    (?, ?, ?, ?, ?, ?, ?)
`

type InsertNodeParams struct {
	ClusterID int64         `json:"cluster_id"`
	Protocol  string        `json:"protocol"`
	Host      string        `json:"host"`
	Port      int64         `json:"port"`
	Weight    int64         `json:"weight"`
	MaxGroups sql.NullInt64 `json:"max_groups"`
	AuthUser  string        `json:"auth_user"`
}

func (q *Queries) InsertNode(ctx context.Context, arg InsertNodeParams) error {
	_, err := q.db.ExecContext(ctx, insertNode,
		arg.ClusterID,
		arg.Protocol,
		arg.Host,
		arg.Port,
		arg.Weight,
		arg.MaxGroups,
		arg.AuthUser,
	)
	return err
}

const insertNodeIntoCluster = `-- name: InsertNodeIntoCluster :one
INSERT INTO
    nodes (
        cluster_id,
        protocol,
        host,
        port,
        weight,
        max_groups,
        auth_user
    )
VALUES
    (?, ?, ?, ?, ?, ?, ?)
RETURNING
    node_id,
    cluster_id,
    protocol,
    auth_user,
    host,
    port,
    weight,
    max_groups
`

type InsertNodeIntoClusterParams struct {
	ClusterID int64         `json:"cluster_id"`
	Protocol  string        `json:"protocol"`
	Host      string        `json:"host"`
	Port      int64         `json:"port"`
	Weight    int64         `json:"weight"`
	MaxGroups sql.NullInt64 `json:"max_groups"`
	AuthUser  string        `json:"auth_user"`
}

func (q *Queries) InsertNodeIntoCluster(ctx context.Context, arg InsertNodeIntoClusterParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, insertNodeIntoCluster,
		arg.ClusterID,
		arg.Protocol,
		arg.Host,
		arg.Port,
		arg.Weight,
		arg.MaxGroups,
		arg.AuthUser,
	)
	var i Node
	err := row.Scan(
		&i.NodeID,
		&i.ClusterID,
		&i.Protocol,
		&i.AuthUser,
		&i.Host,
		&i.Port,
		&i.Weight,
		&i.MaxGroups,
	)
	return i, err
}
