// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	AssignGroupToNode(ctx context.Context, arg AssignGroupToNodeParams) error
	CheckClusterExistsWithData(ctx context.Context, name string) (Cluster, error)
	CheckIfClassExists(ctx context.Context, arg CheckIfClassExistsParams) (int64, error)
	CheckIfClusterExists(ctx context.Context, name string) (int64, error)
	CheckIfNodeExists(ctx context.Context, arg CheckIfNodeExistsParams) (int64, error)
	CreateClass(ctx context.Context, arg CreateClassParams) error
	CreateClassReturning(ctx context.Context, arg CreateClassReturningParams) (int64, error)
	CreateCluster(ctx context.Context, arg CreateClusterParams) (Cluster, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) error
	CreateGroupReturning(ctx context.Context, arg CreateGroupReturningParams) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) error
	CreateUserReturning(ctx context.Context, arg CreateUserReturningParams) (int64, error)
	DeleteClass(ctx context.Context, classID int64) error
	DeleteCluster(ctx context.Context, clusterID int64) error
	DeleteExerciseByName(ctx context.Context, name string) error
	DeleteExerciseForClass(ctx context.Context, name string) error
	DeleteExerciseForClassOnNode(ctx context.Context, arg DeleteExerciseForClassOnNodeParams) error
	DeleteExerciseRecord(ctx context.Context, projectUuid string) error
	DeleteExerciseScoped(ctx context.Context, arg DeleteExerciseScopedParams) error
	DeleteNode(ctx context.Context, nodeID int64) error
	GetAllExerciseNameFromCluster(ctx context.Context, name string) ([]interface{}, error)
	GetClassDisribution(ctx context.Context, clusterID int64) ([]GetClassDisributionRow, error)
	GetClasses(ctx context.Context, clusterID int64) ([]Class, error)
	GetClusterByID(ctx context.Context, name string) (Cluster, error)
	GetClusters(ctx context.Context) ([]Cluster, error)
	GetExercisesForDeletion(ctx context.Context, arg GetExercisesForDeletionParams) ([]GetExercisesForDeletionRow, error)
	GetNodeExercisesForCluster(ctx context.Context, clusterID int64) ([]GetNodeExercisesForClusterRow, error)
	GetNodeGroupAssignments(ctx context.Context, clusterID int64) ([]GetNodeGroupAssignmentsRow, error)
	GetNodeGroupNamesForClass(ctx context.Context, arg GetNodeGroupNamesForClassParams) ([]GetNodeGroupNamesForClassRow, error)
	GetNodes(ctx context.Context) ([]Node, error)
	GetNodesFromClusterID(ctx context.Context, clusterID int64) ([]Node, error)
	InsertExerciseRecord(ctx context.Context, arg InsertExerciseRecordParams) error
	InsertNode(ctx context.Context, arg InsertNodeParams) error
	InsertNodeIntoCluster(ctx context.Context, arg InsertNodeIntoClusterParams) (Node, error)
	NukeEverything(ctx context.Context) error
	UnassignGroupFromNode(ctx context.Context, arg UnassignGroupFromNodeParams) error
	UpdateClusterDescription(ctx context.Context, arg UpdateClusterDescriptionParams) error
	UpdateNode(ctx context.Context, arg UpdateNodeParams) error
}

var _ Querier = (*Queries)(nil)
