// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: updates.sql

package sqlc

import (
	"context"
	"database/sql"
)

const updateClusterDescription = `-- name: UpdateClusterDescription :exec
UPDATE
    clusters
SET
    description = ?
WHERE
    cluster_id = ?
`

type UpdateClusterDescriptionParams struct {
	Description sql.NullString `json:"description"`
	ClusterID   int64          `json:"cluster_id"`
}

func (q *Queries) UpdateClusterDescription(ctx context.Context, arg UpdateClusterDescriptionParams) error {
	_, err := q.db.ExecContext(ctx, updateClusterDescription, arg.Description, arg.ClusterID)
	return err
}

const updateNode = `-- name: UpdateNode :exec
UPDATE
    nodes
SET
    protocol = ?,
    auth_user = ?,
    weight = ?,
    max_groups = ?
WHERE
    cluster_id = ?
    AND host = ?
    AND port = ?
`

type UpdateNodeParams struct {
	Protocol  string        `json:"protocol"`
	AuthUser  string        `json:"auth_user"`
	Weight    int64         `json:"weight"`
	MaxGroups sql.NullInt64 `json:"max_groups"`
	ClusterID int64         `json:"cluster_id"`
	Host      string        `json:"host"`
	Port      int64         `json:"port"`
}

func (q *Queries) UpdateNode(ctx context.Context, arg UpdateNodeParams) error {
	_, err := q.db.ExecContext(ctx, updateNode,
		arg.Protocol,
		arg.AuthUser,
		arg.Weight,
		arg.MaxGroups,
		arg.ClusterID,
		arg.Host,
		arg.Port,
	)
	return err
}
