// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deletes.sql

package sqlc_file_store

import (
	"context"
)

const deleteFilePermanent = `-- name: DeleteFilePermanent :exec
DELETE FROM
    files
WHERE
    file_uuid = ?
`

func (q *Queries) DeleteFilePermanent(ctx context.Context, fileUuid string) error {
	_, err := q.db.ExecContext(ctx, deleteFilePermanent, fileUuid)
	return err
}
