// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inserts.sql

package sqlc_file_store

import (
	"context"
	"database/sql"
)

const createBucket = `-- name: CreateBucket :one
INSERT INTO
    buckets (
        bucket_id,
        name,
        owner_id,
        is_public,
        required_scopes,
        bucket_type
    )
VALUES
    (?, ?, ?, ?, ?, ?)
RETURNING
    bucket_id, name, owner_id, bucket_type, is_public, required_scopes, created_at, updated_at
`

type CreateBucketParams struct {
	BucketID       string         `json:"bucket_id"`
	Name           string         `json:"name"`
	OwnerID        string         `json:"owner_id"`
	IsPublic       sql.NullBool   `json:"is_public"`
	RequiredScopes sql.NullString `json:"required_scopes"`
	BucketType     string         `json:"bucket_type"`
}

func (q *Queries) CreateBucket(ctx context.Context, arg CreateBucketParams) (Bucket, error) {
	row := q.db.QueryRowContext(ctx, createBucket,
		arg.BucketID,
		arg.Name,
		arg.OwnerID,
		arg.IsPublic,
		arg.RequiredScopes,
		arg.BucketType,
	)
	var i Bucket
	err := row.Scan(
		&i.BucketID,
		&i.Name,
		&i.OwnerID,
		&i.BucketType,
		&i.IsPublic,
		&i.RequiredScopes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPublicFileToken = `-- name: CreatePublicFileToken :one
INSERT INTO
    public_file_tokens (
        token,
        file_uuid,
        bucket_id,
        expires_at,
        access_count
    )
VALUES
    (?, ?, ?, ?, 0)
RETURNING
    token, file_uuid, bucket_id, created_at, expires_at, access_count
`

type CreatePublicFileTokenParams struct {
	Token     string `json:"token"`
	FileUuid  string `json:"file_uuid"`
	BucketID  string `json:"bucket_id"`
	ExpiresAt string `json:"expires_at"`
}

func (q *Queries) CreatePublicFileToken(ctx context.Context, arg CreatePublicFileTokenParams) (PublicFileToken, error) {
	row := q.db.QueryRowContext(ctx, createPublicFileToken,
		arg.Token,
		arg.FileUuid,
		arg.BucketID,
		arg.ExpiresAt,
	)
	var i PublicFileToken
	err := row.Scan(
		&i.Token,
		&i.FileUuid,
		&i.BucketID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AccessCount,
	)
	return i, err
}

const initFile = `-- name: InitFile :one
INSERT INTO
    files (
        file_uuid,
        filename,
        content_type,
        owner_id,
        bucket_id,
        last_accessed_at,
        STATUS,
        retention_period
    )
VALUES
    (?, ?, ?, ?, ?, ?, 'pending', ?)
RETURNING
    file_uuid, blob_sha256, filename, content_type, owner_id, bucket_id, created_at, updated_at, last_accessed_at, status, retention_period
`

type InitFileParams struct {
	FileUuid        string        `json:"file_uuid"`
	Filename        string        `json:"filename"`
	ContentType     string        `json:"content_type"`
	OwnerID         string        `json:"owner_id"`
	BucketID        string        `json:"bucket_id"`
	LastAccessedAt  string        `json:"last_accessed_at"`
	RetentionPeriod sql.NullInt64 `json:"retention_period"`
}

func (q *Queries) InitFile(ctx context.Context, arg InitFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, initFile,
		arg.FileUuid,
		arg.Filename,
		arg.ContentType,
		arg.OwnerID,
		arg.BucketID,
		arg.LastAccessedAt,
		arg.RetentionPeriod,
	)
	var i File
	err := row.Scan(
		&i.FileUuid,
		&i.BlobSha256,
		&i.Filename,
		&i.ContentType,
		&i.OwnerID,
		&i.BucketID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAccessedAt,
		&i.Status,
		&i.RetentionPeriod,
	)
	return i, err
}

const insertBackup = `-- name: InsertBackup :exec
INSERT INTO
    backups (
        file_uuid,
        source_node_id,
        backup_type,
        is_compressed,
        is_encrypted,
        parent_backup_uuid
    )
VALUES
    (?, ?, ?, ?, ?, ?)
`

type InsertBackupParams struct {
	FileUuid         string         `json:"file_uuid"`
	SourceNodeID     sql.NullString `json:"source_node_id"`
	BackupType       string         `json:"backup_type"`
	IsCompressed     sql.NullBool   `json:"is_compressed"`
	IsEncrypted      sql.NullBool   `json:"is_encrypted"`
	ParentBackupUuid sql.NullString `json:"parent_backup_uuid"`
}

func (q *Queries) InsertBackup(ctx context.Context, arg InsertBackupParams) error {
	_, err := q.db.ExecContext(ctx, insertBackup,
		arg.FileUuid,
		arg.SourceNodeID,
		arg.BackupType,
		arg.IsCompressed,
		arg.IsEncrypted,
		arg.ParentBackupUuid,
	)
	return err
}

const insertFile = `-- name: InsertFile :exec
INSERT INTO
    files (
        file_uuid,
        blob_sha256,
        filename,
        content_type,
        owner_id,
        bucket_id,
        last_accessed_at,
        STATUS,
        retention_period
    )
VALUES
    (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertFileParams struct {
	FileUuid        string         `json:"file_uuid"`
	BlobSha256      sql.NullString `json:"blob_sha256"`
	Filename        string         `json:"filename"`
	ContentType     string         `json:"content_type"`
	OwnerID         string         `json:"owner_id"`
	BucketID        string         `json:"bucket_id"`
	LastAccessedAt  string         `json:"last_accessed_at"`
	Status          string         `json:"status"`
	RetentionPeriod sql.NullInt64  `json:"retention_period"`
}

func (q *Queries) InsertFile(ctx context.Context, arg InsertFileParams) error {
	_, err := q.db.ExecContext(ctx, insertFile,
		arg.FileUuid,
		arg.BlobSha256,
		arg.Filename,
		arg.ContentType,
		arg.OwnerID,
		arg.BucketID,
		arg.LastAccessedAt,
		arg.Status,
		arg.RetentionPeriod,
	)
	return err
}

const insertProjectFile = `-- name: InsertProjectFile :exec
INSERT INTO
    project_files (
        file_uuid,
        project_id,
        project_name,
        version_tag,
        is_read_only,
        include_snapshots,
        include_images,
        reset_mac_addresses,
        keep_compute_ids,
        compression
    )
VALUES
    (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertProjectFileParams struct {
	FileUuid          string         `json:"file_uuid"`
	ProjectID         string         `json:"project_id"`
	ProjectName       sql.NullString `json:"project_name"`
	VersionTag        sql.NullString `json:"version_tag"`
	IsReadOnly        sql.NullBool   `json:"is_read_only"`
	IncludeSnapshots  bool           `json:"include_snapshots"`
	IncludeImages     bool           `json:"include_images"`
	ResetMacAddresses bool           `json:"reset_mac_addresses"`
	KeepComputeIds    bool           `json:"keep_compute_ids"`
	Compression       string         `json:"compression"`
}

func (q *Queries) InsertProjectFile(ctx context.Context, arg InsertProjectFileParams) error {
	_, err := q.db.ExecContext(ctx, insertProjectFile,
		arg.FileUuid,
		arg.ProjectID,
		arg.ProjectName,
		arg.VersionTag,
		arg.IsReadOnly,
		arg.IncludeSnapshots,
		arg.IncludeImages,
		arg.ResetMacAddresses,
		arg.KeepComputeIds,
		arg.Compression,
	)
	return err
}

const insertVMImage = `-- name: InsertVMImage :exec
INSERT INTO
    vm_images (
        file_uuid,
        virt_type,
        format,
        vcpus,
        ram_mb,
        extra_attributes_json
    )
VALUES
    (?, ?, ?, ?, ?, ?)
`

type InsertVMImageParams struct {
	FileUuid            string         `json:"file_uuid"`
	VirtType            string         `json:"virt_type"`
	Format              string         `json:"format"`
	Vcpus               sql.NullInt64  `json:"vcpus"`
	RamMb               sql.NullInt64  `json:"ram_mb"`
	ExtraAttributesJson sql.NullString `json:"extra_attributes_json"`
}

func (q *Queries) InsertVMImage(ctx context.Context, arg InsertVMImageParams) error {
	_, err := q.db.ExecContext(ctx, insertVMImage,
		arg.FileUuid,
		arg.VirtType,
		arg.Format,
		arg.Vcpus,
		arg.RamMb,
		arg.ExtraAttributesJson,
	)
	return err
}

const upsertBlob = `-- name: UpsertBlob :exec
INSERT INTO
    blobs (
        sha256,
        file_path,
        size_bytes,
        ref_count
    )
VALUES
    (?, ?, ?, 1) ON CONFLICT(sha256) DO
UPDATE
SET
    ref_count = ref_count + 1,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertBlobParams struct {
	Sha256    string `json:"sha256"`
	FilePath  string `json:"file_path"`
	SizeBytes int64  `json:"size_bytes"`
}

func (q *Queries) UpsertBlob(ctx context.Context, arg UpsertBlobParams) error {
	_, err := q.db.ExecContext(ctx, upsertBlob, arg.Sha256, arg.FilePath, arg.SizeBytes)
	return err
}
