// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inserts.sql

package sqlc_file_store

import (
	"context"
	"database/sql"

	"github.com/0xveya/gns3util/pkg/models"
)

const initFile = `-- name: InitFile :one
INSERT INTO
    files (
        file_uuid,
        filename,
        size_bytes,
        content_type,
        scope_label,
        owner_id,
        last_accessed_at,
        STATUS,
        retention_period
    )
VALUES
    (?, ?, ?, ?, ?, ?, ?, 'uploading', ?)
RETURNING
    file_uuid, file_path, filename, size_bytes, checksum_sha256, content_type, scope_label, owner_id, created_at, updated_at, last_accessed_at, status, retention_period
`

type InitFileParams struct {
	FileUuid        string        `json:"file_uuid"`
	Filename        string        `json:"filename"`
	SizeBytes       int64         `json:"size_bytes"`
	ContentType     string        `json:"content_type"`
	ScopeLabel      string        `json:"scope_label"`
	OwnerID         string        `json:"owner_id"`
	LastAccessedAt  sql.NullTime  `json:"last_accessed_at"`
	RetentionPeriod sql.NullInt64 `json:"retention_period"`
}

func (q *Queries) InitFile(ctx context.Context, arg InitFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, initFile,
		arg.FileUuid,
		arg.Filename,
		arg.SizeBytes,
		arg.ContentType,
		arg.ScopeLabel,
		arg.OwnerID,
		arg.LastAccessedAt,
		arg.RetentionPeriod,
	)
	var i File
	err := row.Scan(
		&i.FileUuid,
		&i.FilePath,
		&i.Filename,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.ContentType,
		&i.ScopeLabel,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAccessedAt,
		&i.Status,
		&i.RetentionPeriod,
	)
	return i, err
}

const insertBackup = `-- name: InsertBackup :exec
INSERT INTO
    backups (
        file_uuid,
        source_node_id,
        backup_type,
        is_compressed,
        is_encrypted,
        parent_backup_uuid
    )
VALUES
    (?, ?, ?, ?, ?, ?)
`

type InsertBackupParams struct {
	FileUuid         string         `json:"file_uuid"`
	SourceNodeID     sql.NullString `json:"source_node_id"`
	BackupType       string         `json:"backup_type"`
	IsCompressed     sql.NullBool   `json:"is_compressed"`
	IsEncrypted      sql.NullBool   `json:"is_encrypted"`
	ParentBackupUuid sql.NullString `json:"parent_backup_uuid"`
}

func (q *Queries) InsertBackup(ctx context.Context, arg InsertBackupParams) error {
	_, err := q.db.ExecContext(ctx, insertBackup,
		arg.FileUuid,
		arg.SourceNodeID,
		arg.BackupType,
		arg.IsCompressed,
		arg.IsEncrypted,
		arg.ParentBackupUuid,
	)
	return err
}

const insertFile = `-- name: InsertFile :exec
INSERT INTO
    files (
        file_uuid,
        file_path,
        filename,
        size_bytes,
        checksum_sha256,
        content_type,
        scope_label,
        owner_id,
        last_accessed_at,
        STATUS,
        retention_period
    )
VALUES
    (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertFileParams struct {
	FileUuid        string            `json:"file_uuid"`
	FilePath        string            `json:"file_path"`
	Filename        string            `json:"filename"`
	SizeBytes       int64             `json:"size_bytes"`
	ChecksumSha256  string            `json:"checksum_sha256"`
	ContentType     string            `json:"content_type"`
	ScopeLabel      string            `json:"scope_label"`
	OwnerID         string            `json:"owner_id"`
	LastAccessedAt  sql.NullTime      `json:"last_accessed_at"`
	Status          models.FileStatus `json:"status"`
	RetentionPeriod sql.NullInt64     `json:"retention_period"`
}

func (q *Queries) InsertFile(ctx context.Context, arg InsertFileParams) error {
	_, err := q.db.ExecContext(ctx, insertFile,
		arg.FileUuid,
		arg.FilePath,
		arg.Filename,
		arg.SizeBytes,
		arg.ChecksumSha256,
		arg.ContentType,
		arg.ScopeLabel,
		arg.OwnerID,
		arg.LastAccessedAt,
		arg.Status,
		arg.RetentionPeriod,
	)
	return err
}

const insertProjectFile = `-- name: InsertProjectFile :exec
INSERT INTO
    project_files (
        file_uuid,
        project_id,
        version_tag,
        is_read_only
    )
VALUES
    (?, ?, ?, ?)
`

type InsertProjectFileParams struct {
	FileUuid   string         `json:"file_uuid"`
	ProjectID  string         `json:"project_id"`
	VersionTag sql.NullString `json:"version_tag"`
	IsReadOnly sql.NullBool   `json:"is_read_only"`
}

func (q *Queries) InsertProjectFile(ctx context.Context, arg InsertProjectFileParams) error {
	_, err := q.db.ExecContext(ctx, insertProjectFile,
		arg.FileUuid,
		arg.ProjectID,
		arg.VersionTag,
		arg.IsReadOnly,
	)
	return err
}

const insertVMImage = `-- name: InsertVMImage :exec
INSERT INTO
    vm_images (
        file_uuid,
        virt_type,
        format,
        vcpus,
        ram_mb,
        extra_attributes_json
    )
VALUES
    (?, ?, ?, ?, ?, ?)
`

type InsertVMImageParams struct {
	FileUuid            string         `json:"file_uuid"`
	VirtType            string         `json:"virt_type"`
	Format              string         `json:"format"`
	Vcpus               sql.NullInt64  `json:"vcpus"`
	RamMb               sql.NullInt64  `json:"ram_mb"`
	ExtraAttributesJson sql.NullString `json:"extra_attributes_json"`
}

func (q *Queries) InsertVMImage(ctx context.Context, arg InsertVMImageParams) error {
	_, err := q.db.ExecContext(ctx, insertVMImage,
		arg.FileUuid,
		arg.VirtType,
		arg.Format,
		arg.Vcpus,
		arg.RamMb,
		arg.ExtraAttributesJson,
	)
	return err
}
