// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc_file_store

import (
	"database/sql"
)

type Backup struct {
	FileUuid         string
	SourceNodeID     sql.NullString
	BackupType       string
	IsCompressed     sql.NullBool
	IsEncrypted      sql.NullBool
	ParentBackupUuid sql.NullString
}

type File struct {
	FileUuid        string
	FilePath        string
	Filename        string
	SizeBytes       int64
	ChecksumSha256  string
	ContentType     string
	ScopeLabel      string
	OwnerID         string
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	LastAccessedAt  sql.NullTime
	Status          sql.NullString
	RetentionPeriod sql.NullInt64
}

type ProjectFile struct {
	FileUuid   string
	ProjectID  string
	VersionTag sql.NullString
	IsReadOnly sql.NullBool
}

type VmImage struct {
	FileUuid            string
	VirtType            string
	Format              string
	Vcpus               sql.NullInt64
	RamMb               sql.NullInt64
	ExtraAttributesJson sql.NullString
}
