// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc_file_store

import (
	"database/sql"

	"github.com/0xveya/gns3util/pkg/models"
)

type Backup struct {
	FileUuid         string         `json:"file_uuid"`
	SourceNodeID     sql.NullString `json:"source_node_id"`
	BackupType       string         `json:"backup_type"`
	IsCompressed     sql.NullBool   `json:"is_compressed"`
	IsEncrypted      sql.NullBool   `json:"is_encrypted"`
	ParentBackupUuid sql.NullString `json:"parent_backup_uuid"`
}

type Bucket struct {
	BucketID       string         `json:"bucket_id"`
	Name           string         `json:"name"`
	OwnerID        string         `json:"owner_id"`
	BucketType     string         `json:"bucket_type"`
	IsPublic       sql.NullBool   `json:"is_public"`
	RequiredScopes sql.NullString `json:"required_scopes"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

type File struct {
	FileUuid        string            `json:"file_uuid"`
	FilePath        string            `json:"file_path"`
	Filename        string            `json:"filename"`
	SizeBytes       int64             `json:"size_bytes"`
	ChecksumSha256  string            `json:"checksum_sha256"`
	ContentType     string            `json:"content_type"`
	ScopeLabel      string            `json:"scope_label"`
	OwnerID         string            `json:"owner_id"`
	BucketID        string            `json:"bucket_id"`
	CreatedAt       sql.NullTime      `json:"created_at"`
	UpdatedAt       sql.NullTime      `json:"updated_at"`
	LastAccessedAt  sql.NullTime      `json:"last_accessed_at"`
	Status          models.FileStatus `json:"status"`
	RetentionPeriod sql.NullInt64     `json:"retention_period"`
}

type ProjectFile struct {
	FileUuid   string         `json:"file_uuid"`
	ProjectID  string         `json:"project_id"`
	VersionTag sql.NullString `json:"version_tag"`
	IsReadOnly sql.NullBool   `json:"is_read_only"`
}

type PublicFileToken struct {
	Token       string        `json:"token"`
	FileUuid    string        `json:"file_uuid"`
	BucketID    string        `json:"bucket_id"`
	CreatedAt   sql.NullTime  `json:"created_at"`
	ExpiresAt   sql.NullTime  `json:"expires_at"`
	AccessCount sql.NullInt64 `json:"access_count"`
}

type VmImage struct {
	FileUuid            string         `json:"file_uuid"`
	VirtType            string         `json:"virt_type"`
	Format              string         `json:"format"`
	Vcpus               sql.NullInt64  `json:"vcpus"`
	RamMb               sql.NullInt64  `json:"ram_mb"`
	ExtraAttributesJson sql.NullString `json:"extra_attributes_json"`
}
