// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permissions.sql

package sqlc_file_store

import (
	"context"
)

const deleteBucketPermission = `-- name: DeleteBucketPermission :exec
DELETE FROM bucket_permissions
WHERE id = ? AND bucket_id = ?
`

type DeleteBucketPermissionParams struct {
	ID       string `json:"id"`
	BucketID string `json:"bucket_id"`
}

func (q *Queries) DeleteBucketPermission(ctx context.Context, arg DeleteBucketPermissionParams) error {
	_, err := q.db.ExecContext(ctx, deleteBucketPermission, arg.ID, arg.BucketID)
	return err
}

const deleteFilePermission = `-- name: DeleteFilePermission :exec
DELETE FROM file_permissions
WHERE id = ? AND file_uuid = ?
`

type DeleteFilePermissionParams struct {
	ID       string `json:"id"`
	FileUuid string `json:"file_uuid"`
}

func (q *Queries) DeleteFilePermission(ctx context.Context, arg DeleteFilePermissionParams) error {
	_, err := q.db.ExecContext(ctx, deleteFilePermission, arg.ID, arg.FileUuid)
	return err
}

const getBucketPermission = `-- name: GetBucketPermission :one
SELECT
    id,
    bucket_id,
    principal_type,
    principal_id,
    permission,
    granted_by,
    created_at,
    expires_at
FROM bucket_permissions
WHERE id = ?
`

func (q *Queries) GetBucketPermission(ctx context.Context, id string) (BucketPermission, error) {
	row := q.db.QueryRowContext(ctx, getBucketPermission, id)
	var i BucketPermission
	err := row.Scan(
		&i.ID,
		&i.BucketID,
		&i.PrincipalType,
		&i.PrincipalID,
		&i.Permission,
		&i.GrantedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getFilePermission = `-- name: GetFilePermission :one
SELECT
    id,
    file_uuid,
    principal_type,
    principal_id,
    permission,
    granted_by,
    created_at,
    expires_at
FROM file_permissions
WHERE id = ?
`

func (q *Queries) GetFilePermission(ctx context.Context, id string) (FilePermission, error) {
	row := q.db.QueryRowContext(ctx, getFilePermission, id)
	var i FilePermission
	err := row.Scan(
		&i.ID,
		&i.FileUuid,
		&i.PrincipalType,
		&i.PrincipalID,
		&i.Permission,
		&i.GrantedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const hasBucketPermission = `-- name: HasBucketPermission :one
SELECT COUNT(*) > 0 AS has_permission
FROM bucket_permissions
WHERE bucket_id = ?
  AND principal_type = 'user'
  AND principal_id = ?
  AND permission = ?
  AND (expires_at IS NULL OR expires_at = '' OR expires_at > CURRENT_TIMESTAMP)
`

type HasBucketPermissionParams struct {
	BucketID    string `json:"bucket_id"`
	PrincipalID string `json:"principal_id"`
	Permission  string `json:"permission"`
}

func (q *Queries) HasBucketPermission(ctx context.Context, arg HasBucketPermissionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasBucketPermission, arg.BucketID, arg.PrincipalID, arg.Permission)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}

const hasFilePermission = `-- name: HasFilePermission :one
SELECT COUNT(*) > 0 AS has_permission
FROM file_permissions
WHERE file_uuid = ?
  AND principal_type = 'user'
  AND principal_id = ?
  AND permission = ?
  AND (expires_at IS NULL OR expires_at = '' OR expires_at > CURRENT_TIMESTAMP)
`

type HasFilePermissionParams struct {
	FileUuid    string `json:"file_uuid"`
	PrincipalID string `json:"principal_id"`
	Permission  string `json:"permission"`
}

func (q *Queries) HasFilePermission(ctx context.Context, arg HasFilePermissionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasFilePermission, arg.FileUuid, arg.PrincipalID, arg.Permission)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}

const insertBucketPermission = `-- name: InsertBucketPermission :one
INSERT INTO bucket_permissions (
    id,
    bucket_id,
    principal_type,
    principal_id,
    permission,
    granted_by,
    expires_at
)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, bucket_id, principal_type, principal_id, permission, granted_by, created_at, expires_at
`

type InsertBucketPermissionParams struct {
	ID            string `json:"id"`
	BucketID      string `json:"bucket_id"`
	PrincipalType string `json:"principal_type"`
	PrincipalID   string `json:"principal_id"`
	Permission    string `json:"permission"`
	GrantedBy     string `json:"granted_by"`
	ExpiresAt     string `json:"expires_at"`
}

func (q *Queries) InsertBucketPermission(ctx context.Context, arg InsertBucketPermissionParams) (BucketPermission, error) {
	row := q.db.QueryRowContext(ctx, insertBucketPermission,
		arg.ID,
		arg.BucketID,
		arg.PrincipalType,
		arg.PrincipalID,
		arg.Permission,
		arg.GrantedBy,
		arg.ExpiresAt,
	)
	var i BucketPermission
	err := row.Scan(
		&i.ID,
		&i.BucketID,
		&i.PrincipalType,
		&i.PrincipalID,
		&i.Permission,
		&i.GrantedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertFilePermission = `-- name: InsertFilePermission :one
INSERT INTO file_permissions (
    id,
    file_uuid,
    principal_type,
    principal_id,
    permission,
    granted_by,
    expires_at
)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, file_uuid, principal_type, principal_id, permission, granted_by, created_at, expires_at
`

type InsertFilePermissionParams struct {
	ID            string `json:"id"`
	FileUuid      string `json:"file_uuid"`
	PrincipalType string `json:"principal_type"`
	PrincipalID   string `json:"principal_id"`
	Permission    string `json:"permission"`
	GrantedBy     string `json:"granted_by"`
	ExpiresAt     string `json:"expires_at"`
}

func (q *Queries) InsertFilePermission(ctx context.Context, arg InsertFilePermissionParams) (FilePermission, error) {
	row := q.db.QueryRowContext(ctx, insertFilePermission,
		arg.ID,
		arg.FileUuid,
		arg.PrincipalType,
		arg.PrincipalID,
		arg.Permission,
		arg.GrantedBy,
		arg.ExpiresAt,
	)
	var i FilePermission
	err := row.Scan(
		&i.ID,
		&i.FileUuid,
		&i.PrincipalType,
		&i.PrincipalID,
		&i.Permission,
		&i.GrantedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listBucketPermissions = `-- name: ListBucketPermissions :many
SELECT
    id,
    bucket_id,
    principal_type,
    principal_id,
    permission,
    granted_by,
    created_at,
    expires_at
FROM bucket_permissions
WHERE bucket_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListBucketPermissions(ctx context.Context, bucketID string) ([]BucketPermission, error) {
	rows, err := q.db.QueryContext(ctx, listBucketPermissions, bucketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BucketPermission{}
	for rows.Next() {
		var i BucketPermission
		if err := rows.Scan(
			&i.ID,
			&i.BucketID,
			&i.PrincipalType,
			&i.PrincipalID,
			&i.Permission,
			&i.GrantedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilePermissions = `-- name: ListFilePermissions :many
SELECT
    id,
    file_uuid,
    principal_type,
    principal_id,
    permission,
    granted_by,
    created_at,
    expires_at
FROM file_permissions
WHERE file_uuid = ?
ORDER BY created_at DESC
`

func (q *Queries) ListFilePermissions(ctx context.Context, fileUuid string) ([]FilePermission, error) {
	rows, err := q.db.QueryContext(ctx, listFilePermissions, fileUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FilePermission{}
	for rows.Next() {
		var i FilePermission
		if err := rows.Scan(
			&i.ID,
			&i.FileUuid,
			&i.PrincipalType,
			&i.PrincipalID,
			&i.Permission,
			&i.GrantedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
