// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc_file_store

import (
	"context"
)

type Querier interface {
	DeleteFile(ctx context.Context, fileUuid string) error
	FinalizeFile(ctx context.Context, arg FinalizeFileParams) (File, error)
	GetBackupByFileUUID(ctx context.Context, fileUuid string) (Backup, error)
	GetFileByUUID(ctx context.Context, fileUuid string) (File, error)
	GetOwnerOfFileByUUID(ctx context.Context, fileUuid string) (string, error)
	GetProjectFileByFileUUID(ctx context.Context, fileUuid string) (ProjectFile, error)
	GetVMImageByFileUUID(ctx context.Context, fileUuid string) (VmImage, error)
	InitFile(ctx context.Context, arg InitFileParams) (File, error)
	InsertBackup(ctx context.Context, arg InsertBackupParams) error
	InsertFile(ctx context.Context, arg InsertFileParams) error
	InsertProjectFile(ctx context.Context, arg InsertProjectFileParams) error
	InsertVMImage(ctx context.Context, arg InsertVMImageParams) error
	ListFiles(ctx context.Context) ([]File, error)
	ListFilesByOwner(ctx context.Context, ownerID string) ([]File, error)
	ListFilesByScope(ctx context.Context, scopeLabel string) ([]File, error)
	MarkFileTombstoned(ctx context.Context, fileUuid string) error
	UpdateFileLastAccessedAt(ctx context.Context, fileUuid string) error
	UpdateFileMetadata(ctx context.Context, arg UpdateFileMetadataParams) error
	UpdateFileStatus(ctx context.Context, arg UpdateFileStatusParams) error
}

var _ Querier = (*Queries)(nil)
