// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc_file_store

import (
	"context"
)

type Querier interface {
	CreateBucket(ctx context.Context, arg CreateBucketParams) (Bucket, error)
	CreatePublicFileToken(ctx context.Context, arg CreatePublicFileTokenParams) (PublicFileToken, error)
	DecrementBlobRefCount(ctx context.Context, sha256 string) error
	DeleteBackup(ctx context.Context, fileUuid string) error
	DeleteBlob(ctx context.Context, sha256 string) error
	DeleteBlobIfUnreferenced(ctx context.Context, sha256 string) error
	DeleteBucket(ctx context.Context, bucketID string) error
	DeleteBucketPermission(ctx context.Context, arg DeleteBucketPermissionParams) error
	DeleteExpiredPublicTokens(ctx context.Context) error
	DeleteFile(ctx context.Context, fileUuid string) error
	DeleteFilePermission(ctx context.Context, arg DeleteFilePermissionParams) error
	DeleteProjectFile(ctx context.Context, fileUuid string) error
	DeletePublicFileToken(ctx context.Context, token string) error
	DeleteVMImage(ctx context.Context, fileUuid string) error
	FinalizeFile(ctx context.Context, arg FinalizeFileParams) (File, error)
	GetBackupByFileUUID(ctx context.Context, fileUuid string) (Backup, error)
	GetBlobByFileUUID(ctx context.Context, fileUuid string) (GetBlobByFileUUIDRow, error)
	GetBlobBySHA256(ctx context.Context, sha256 string) (Blob, error)
	GetBucketByID(ctx context.Context, bucketID string) (GetBucketByIDRow, error)
	GetBucketPermission(ctx context.Context, id string) (BucketPermission, error)
	GetDefaultBucketForOwner(ctx context.Context, ownerID string) (GetDefaultBucketForOwnerRow, error)
	GetFileByUUID(ctx context.Context, fileUuid string) (File, error)
	GetFilePermission(ctx context.Context, id string) (FilePermission, error)
	GetFileWithBlobByUUID(ctx context.Context, fileUuid string) (GetFileWithBlobByUUIDRow, error)
	GetFilesWithPassedRetention(ctx context.Context) ([]string, error)
	GetFilesWithStatus(ctx context.Context, status string) ([]File, error)
	GetOwnerOfFileByUUID(ctx context.Context, fileUuid string) (string, error)
	GetProjectFileByFileUUID(ctx context.Context, fileUuid string) (ProjectFile, error)
	GetPublicFileToken(ctx context.Context, token string) (PublicFileToken, error)
	GetPublicFileTokens(ctx context.Context, fileUuid string) ([]PublicFileToken, error)
	GetUnreferencedBlobs(ctx context.Context) ([]GetUnreferencedBlobsRow, error)
	GetVMImageByFileUUID(ctx context.Context, fileUuid string) (VmImage, error)
	HasBucketPermission(ctx context.Context, arg HasBucketPermissionParams) (bool, error)
	HasFilePermission(ctx context.Context, arg HasFilePermissionParams) (bool, error)
	IncrementBlobRefCount(ctx context.Context, sha256 string) error
	IncrementTokenAccessCount(ctx context.Context, token string) error
	InitFile(ctx context.Context, arg InitFileParams) (File, error)
	InsertBackup(ctx context.Context, arg InsertBackupParams) error
	InsertBucketPermission(ctx context.Context, arg InsertBucketPermissionParams) (BucketPermission, error)
	InsertFile(ctx context.Context, arg InsertFileParams) error
	InsertFilePermission(ctx context.Context, arg InsertFilePermissionParams) (FilePermission, error)
	InsertProjectFile(ctx context.Context, arg InsertProjectFileParams) error
	InsertVMImage(ctx context.Context, arg InsertVMImageParams) error
	ListBucketPermissions(ctx context.Context, bucketID string) ([]BucketPermission, error)
	ListBucketsByOwner(ctx context.Context, ownerID string) ([]ListBucketsByOwnerRow, error)
	ListFilePermissions(ctx context.Context, fileUuid string) ([]FilePermission, error)
	ListFiles(ctx context.Context) ([]File, error)
	ListFilesByBucket(ctx context.Context, bucketID string) ([]File, error)
	ListFilesByBucketWithBlob(ctx context.Context, bucketID string) ([]ListFilesByBucketWithBlobRow, error)
	ListFilesByOwner(ctx context.Context, ownerID string) ([]File, error)
	MarkFileTombstoned(ctx context.Context, fileUuid string) error
	UpdateBucket(ctx context.Context, arg UpdateBucketParams) error
	UpdateFileBucket(ctx context.Context, arg UpdateFileBucketParams) error
	UpdateFileLastAccessedAt(ctx context.Context, fileUuid string) error
	UpdateFileMetadata(ctx context.Context, arg UpdateFileMetadataParams) error
	UpdateFileStatus(ctx context.Context, arg UpdateFileStatusParams) error
	UpsertBlob(ctx context.Context, arg UpsertBlobParams) error
}

var _ Querier = (*Queries)(nil)
