// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: selects.sql

package sqlc_file_store

import (
	"context"
	"database/sql"
)

const getBackupByFileUUID = `-- name: GetBackupByFileUUID :one
SELECT
    file_uuid,
    source_node_id,
    backup_type,
    is_compressed,
    is_encrypted,
    parent_backup_uuid
FROM
    backups
WHERE
    file_uuid = ?
`

func (q *Queries) GetBackupByFileUUID(ctx context.Context, fileUuid string) (Backup, error) {
	row := q.db.QueryRowContext(ctx, getBackupByFileUUID, fileUuid)
	var i Backup
	err := row.Scan(
		&i.FileUuid,
		&i.SourceNodeID,
		&i.BackupType,
		&i.IsCompressed,
		&i.IsEncrypted,
		&i.ParentBackupUuid,
	)
	return i, err
}

const getBackupWithFile = `-- name: GetBackupWithFile :one
SELECT
    f.file_uuid,
    f.filename,
    f.content_type,
    f.owner_id,
    f.bucket_id,
    f.created_at,
    f.updated_at,
    f.status,
    f.retention_period,
    f.blob_sha256,
    b.size_bytes,
    bk.source_node_id,
    bk.backup_type,
    bk.is_compressed,
    bk.is_encrypted,
    bk.parent_backup_uuid
FROM
    backups bk
    JOIN files f ON f.file_uuid = bk.file_uuid
    LEFT JOIN blobs b ON b.sha256 = f.blob_sha256
WHERE
    bk.file_uuid = ?
`

type GetBackupWithFileRow struct {
	FileUuid         string         `json:"file_uuid"`
	Filename         string         `json:"filename"`
	ContentType      string         `json:"content_type"`
	OwnerID          string         `json:"owner_id"`
	BucketID         string         `json:"bucket_id"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
	Status           string         `json:"status"`
	RetentionPeriod  sql.NullInt64  `json:"retention_period"`
	BlobSha256       sql.NullString `json:"blob_sha256"`
	SizeBytes        sql.NullInt64  `json:"size_bytes"`
	SourceNodeID     sql.NullString `json:"source_node_id"`
	BackupType       string         `json:"backup_type"`
	IsCompressed     sql.NullBool   `json:"is_compressed"`
	IsEncrypted      sql.NullBool   `json:"is_encrypted"`
	ParentBackupUuid sql.NullString `json:"parent_backup_uuid"`
}

func (q *Queries) GetBackupWithFile(ctx context.Context, fileUuid string) (GetBackupWithFileRow, error) {
	row := q.db.QueryRowContext(ctx, getBackupWithFile, fileUuid)
	var i GetBackupWithFileRow
	err := row.Scan(
		&i.FileUuid,
		&i.Filename,
		&i.ContentType,
		&i.OwnerID,
		&i.BucketID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.RetentionPeriod,
		&i.BlobSha256,
		&i.SizeBytes,
		&i.SourceNodeID,
		&i.BackupType,
		&i.IsCompressed,
		&i.IsEncrypted,
		&i.ParentBackupUuid,
	)
	return i, err
}

const getBlobByFileUUID = `-- name: GetBlobByFileUUID :one
SELECT
    blob_sha256,
    blobs.file_path
FROM
    files
    JOIN blobs ON blobs.sha256 = files.blob_sha256
WHERE
    file_uuid = ?
`

type GetBlobByFileUUIDRow struct {
	BlobSha256 sql.NullString `json:"blob_sha256"`
	FilePath   string         `json:"file_path"`
}

func (q *Queries) GetBlobByFileUUID(ctx context.Context, fileUuid string) (GetBlobByFileUUIDRow, error) {
	row := q.db.QueryRowContext(ctx, getBlobByFileUUID, fileUuid)
	var i GetBlobByFileUUIDRow
	err := row.Scan(&i.BlobSha256, &i.FilePath)
	return i, err
}

const getBlobBySHA256 = `-- name: GetBlobBySHA256 :one
SELECT
    sha256,
    file_path,
    size_bytes,
    ref_count,
    created_at,
    updated_at,
    last_verified_at
FROM
    blobs
WHERE
    sha256 = ?
`

func (q *Queries) GetBlobBySHA256(ctx context.Context, sha256 string) (Blob, error) {
	row := q.db.QueryRowContext(ctx, getBlobBySHA256, sha256)
	var i Blob
	err := row.Scan(
		&i.Sha256,
		&i.FilePath,
		&i.SizeBytes,
		&i.RefCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastVerifiedAt,
	)
	return i, err
}

const getBucketByID = `-- name: GetBucketByID :one
SELECT
    bucket_id,
    name,
    owner_id,
    is_public,
    required_scopes,
    created_at,
    updated_at
FROM
    buckets
WHERE
    bucket_id = ?
`

type GetBucketByIDRow struct {
	BucketID       string         `json:"bucket_id"`
	Name           string         `json:"name"`
	OwnerID        string         `json:"owner_id"`
	IsPublic       sql.NullBool   `json:"is_public"`
	RequiredScopes sql.NullString `json:"required_scopes"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
}

func (q *Queries) GetBucketByID(ctx context.Context, bucketID string) (GetBucketByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getBucketByID, bucketID)
	var i GetBucketByIDRow
	err := row.Scan(
		&i.BucketID,
		&i.Name,
		&i.OwnerID,
		&i.IsPublic,
		&i.RequiredScopes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefaultBucketForOwner = `-- name: GetDefaultBucketForOwner :one
SELECT
    bucket_id,
    name,
    owner_id,
    is_public,
    required_scopes,
    created_at,
    updated_at
FROM
    buckets
WHERE
    owner_id = ?
    AND name = 'default'
LIMIT
    1
`

type GetDefaultBucketForOwnerRow struct {
	BucketID       string         `json:"bucket_id"`
	Name           string         `json:"name"`
	OwnerID        string         `json:"owner_id"`
	IsPublic       sql.NullBool   `json:"is_public"`
	RequiredScopes sql.NullString `json:"required_scopes"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
}

func (q *Queries) GetDefaultBucketForOwner(ctx context.Context, ownerID string) (GetDefaultBucketForOwnerRow, error) {
	row := q.db.QueryRowContext(ctx, getDefaultBucketForOwner, ownerID)
	var i GetDefaultBucketForOwnerRow
	err := row.Scan(
		&i.BucketID,
		&i.Name,
		&i.OwnerID,
		&i.IsPublic,
		&i.RequiredScopes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFileByUUID = `-- name: GetFileByUUID :one
SELECT
    file_uuid,
    blob_sha256,
    filename,
    content_type,
    owner_id,
    bucket_id,
    created_at,
    updated_at,
    last_accessed_at,
    STATUS,
    retention_period
FROM
    files
WHERE
    file_uuid = ?
`

func (q *Queries) GetFileByUUID(ctx context.Context, fileUuid string) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileByUUID, fileUuid)
	var i File
	err := row.Scan(
		&i.FileUuid,
		&i.BlobSha256,
		&i.Filename,
		&i.ContentType,
		&i.OwnerID,
		&i.BucketID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAccessedAt,
		&i.Status,
		&i.RetentionPeriod,
	)
	return i, err
}

const getFileWithBlobByUUID = `-- name: GetFileWithBlobByUUID :one
SELECT
    f.file_uuid,
    f.blob_sha256,
    f.filename,
    f.content_type,
    f.owner_id,
    f.bucket_id,
    f.created_at,
    f.updated_at,
    f.last_accessed_at,
    f.status,
    f.retention_period,
    b.file_path,
    b.size_bytes,
    b.ref_count
FROM
    files f
    JOIN blobs b ON b.sha256 = f.blob_sha256
WHERE
    f.file_uuid = ?
`

type GetFileWithBlobByUUIDRow struct {
	FileUuid        string         `json:"file_uuid"`
	BlobSha256      sql.NullString `json:"blob_sha256"`
	Filename        string         `json:"filename"`
	ContentType     string         `json:"content_type"`
	OwnerID         string         `json:"owner_id"`
	BucketID        string         `json:"bucket_id"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
	LastAccessedAt  string         `json:"last_accessed_at"`
	Status          string         `json:"status"`
	RetentionPeriod sql.NullInt64  `json:"retention_period"`
	FilePath        string         `json:"file_path"`
	SizeBytes       int64          `json:"size_bytes"`
	RefCount        int64          `json:"ref_count"`
}

func (q *Queries) GetFileWithBlobByUUID(ctx context.Context, fileUuid string) (GetFileWithBlobByUUIDRow, error) {
	row := q.db.QueryRowContext(ctx, getFileWithBlobByUUID, fileUuid)
	var i GetFileWithBlobByUUIDRow
	err := row.Scan(
		&i.FileUuid,
		&i.BlobSha256,
		&i.Filename,
		&i.ContentType,
		&i.OwnerID,
		&i.BucketID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAccessedAt,
		&i.Status,
		&i.RetentionPeriod,
		&i.FilePath,
		&i.SizeBytes,
		&i.RefCount,
	)
	return i, err
}

const getFilesWithPassedRetention = `-- name: GetFilesWithPassedRetention :many
SELECT
    file_uuid
FROM
    files
WHERE
    retention_period > 0
    AND datetime(created_at, '+' || retention_period || ' hours') < datetime('now')
`

func (q *Queries) GetFilesWithPassedRetention(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getFilesWithPassedRetention)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var file_uuid string
		if err := rows.Scan(&file_uuid); err != nil {
			return nil, err
		}
		items = append(items, file_uuid)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesWithStatus = `-- name: GetFilesWithStatus :many
SELECT
    file_uuid,
    blob_sha256,
    filename,
    content_type,
    owner_id,
    bucket_id,
    created_at,
    updated_at,
    last_accessed_at,
    STATUS,
    retention_period
FROM
    files
WHERE
    STATUS = ?
`

func (q *Queries) GetFilesWithStatus(ctx context.Context, status string) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, getFilesWithStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.FileUuid,
			&i.BlobSha256,
			&i.Filename,
			&i.ContentType,
			&i.OwnerID,
			&i.BucketID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastAccessedAt,
			&i.Status,
			&i.RetentionPeriod,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOwnerOfFileByUUID = `-- name: GetOwnerOfFileByUUID :one
SELECT
    owner_id
FROM
    files
WHERE
    file_uuid = ?
`

func (q *Queries) GetOwnerOfFileByUUID(ctx context.Context, fileUuid string) (string, error) {
	row := q.db.QueryRowContext(ctx, getOwnerOfFileByUUID, fileUuid)
	var owner_id string
	err := row.Scan(&owner_id)
	return owner_id, err
}

const getProjectFileByFileUUID = `-- name: GetProjectFileByFileUUID :one
SELECT
    file_uuid,
    project_id,
    version_tag,
    is_read_only
FROM
    project_files
WHERE
    file_uuid = ?
`

type GetProjectFileByFileUUIDRow struct {
	FileUuid   string         `json:"file_uuid"`
	ProjectID  string         `json:"project_id"`
	VersionTag sql.NullString `json:"version_tag"`
	IsReadOnly sql.NullBool   `json:"is_read_only"`
}

func (q *Queries) GetProjectFileByFileUUID(ctx context.Context, fileUuid string) (GetProjectFileByFileUUIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectFileByFileUUID, fileUuid)
	var i GetProjectFileByFileUUIDRow
	err := row.Scan(
		&i.FileUuid,
		&i.ProjectID,
		&i.VersionTag,
		&i.IsReadOnly,
	)
	return i, err
}

const getProjectFileWithFile = `-- name: GetProjectFileWithFile :one
SELECT
    f.file_uuid,
    f.filename,
    f.content_type,
    f.owner_id,
    f.bucket_id,
    f.created_at,
    f.updated_at,
    f.status,
    f.retention_period,
    f.blob_sha256,
    b.size_bytes,
    pf.project_id,
    pf.project_name,
    pf.version_tag,
    pf.is_read_only,
    pf.include_snapshots,
    pf.include_images,
    pf.reset_mac_addresses,
    pf.keep_compute_ids,
    pf.compression
FROM
    project_files pf
    JOIN files f ON f.file_uuid = pf.file_uuid
    LEFT JOIN blobs b ON b.sha256 = f.blob_sha256
WHERE
    pf.file_uuid = ?
`

type GetProjectFileWithFileRow struct {
	FileUuid          string         `json:"file_uuid"`
	Filename          string         `json:"filename"`
	ContentType       string         `json:"content_type"`
	OwnerID           string         `json:"owner_id"`
	BucketID          string         `json:"bucket_id"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
	Status            string         `json:"status"`
	RetentionPeriod   sql.NullInt64  `json:"retention_period"`
	BlobSha256        sql.NullString `json:"blob_sha256"`
	SizeBytes         sql.NullInt64  `json:"size_bytes"`
	ProjectID         string         `json:"project_id"`
	ProjectName       sql.NullString `json:"project_name"`
	VersionTag        sql.NullString `json:"version_tag"`
	IsReadOnly        sql.NullBool   `json:"is_read_only"`
	IncludeSnapshots  bool           `json:"include_snapshots"`
	IncludeImages     bool           `json:"include_images"`
	ResetMacAddresses bool           `json:"reset_mac_addresses"`
	KeepComputeIds    bool           `json:"keep_compute_ids"`
	Compression       string         `json:"compression"`
}

func (q *Queries) GetProjectFileWithFile(ctx context.Context, fileUuid string) (GetProjectFileWithFileRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectFileWithFile, fileUuid)
	var i GetProjectFileWithFileRow
	err := row.Scan(
		&i.FileUuid,
		&i.Filename,
		&i.ContentType,
		&i.OwnerID,
		&i.BucketID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.RetentionPeriod,
		&i.BlobSha256,
		&i.SizeBytes,
		&i.ProjectID,
		&i.ProjectName,
		&i.VersionTag,
		&i.IsReadOnly,
		&i.IncludeSnapshots,
		&i.IncludeImages,
		&i.ResetMacAddresses,
		&i.KeepComputeIds,
		&i.Compression,
	)
	return i, err
}

const getPublicFileToken = `-- name: GetPublicFileToken :one
SELECT
    token,
    file_uuid,
    bucket_id,
    created_at,
    expires_at,
    access_count
FROM
    public_file_tokens
WHERE
    token = ?
`

func (q *Queries) GetPublicFileToken(ctx context.Context, token string) (PublicFileToken, error) {
	row := q.db.QueryRowContext(ctx, getPublicFileToken, token)
	var i PublicFileToken
	err := row.Scan(
		&i.Token,
		&i.FileUuid,
		&i.BucketID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AccessCount,
	)
	return i, err
}

const getPublicFileTokens = `-- name: GetPublicFileTokens :many
SELECT
    token,
    file_uuid,
    bucket_id,
    created_at,
    expires_at,
    access_count
FROM
    public_file_tokens
WHERE
    file_uuid = ?
ORDER BY
    created_at DESC
`

func (q *Queries) GetPublicFileTokens(ctx context.Context, fileUuid string) ([]PublicFileToken, error) {
	rows, err := q.db.QueryContext(ctx, getPublicFileTokens, fileUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublicFileToken{}
	for rows.Next() {
		var i PublicFileToken
		if err := rows.Scan(
			&i.Token,
			&i.FileUuid,
			&i.BucketID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.AccessCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreferencedBlobs = `-- name: GetUnreferencedBlobs :many
SELECT
    sha256,
    file_path
FROM
    blobs
WHERE
    ref_count <= 0
`

type GetUnreferencedBlobsRow struct {
	Sha256   string `json:"sha256"`
	FilePath string `json:"file_path"`
}

func (q *Queries) GetUnreferencedBlobs(ctx context.Context) ([]GetUnreferencedBlobsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUnreferencedBlobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUnreferencedBlobsRow{}
	for rows.Next() {
		var i GetUnreferencedBlobsRow
		if err := rows.Scan(&i.Sha256, &i.FilePath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVMImageByFileUUID = `-- name: GetVMImageByFileUUID :one
SELECT
    file_uuid,
    virt_type,
    format,
    vcpus,
    ram_mb,
    extra_attributes_json
FROM
    vm_images
WHERE
    file_uuid = ?
`

func (q *Queries) GetVMImageByFileUUID(ctx context.Context, fileUuid string) (VmImage, error) {
	row := q.db.QueryRowContext(ctx, getVMImageByFileUUID, fileUuid)
	var i VmImage
	err := row.Scan(
		&i.FileUuid,
		&i.VirtType,
		&i.Format,
		&i.Vcpus,
		&i.RamMb,
		&i.ExtraAttributesJson,
	)
	return i, err
}

const getVMImageWithFile = `-- name: GetVMImageWithFile :one
SELECT
    f.file_uuid,
    f.filename,
    f.content_type,
    f.owner_id,
    f.bucket_id,
    f.created_at,
    f.updated_at,
    f.status,
    f.retention_period,
    f.blob_sha256,
    b.size_bytes,
    v.virt_type,
    v.format,
    v.vcpus,
    v.ram_mb,
    v.extra_attributes_json
FROM
    vm_images v
    JOIN files f ON f.file_uuid = v.file_uuid
    LEFT JOIN blobs b ON b.sha256 = f.blob_sha256
WHERE
    v.file_uuid = ?
`

type GetVMImageWithFileRow struct {
	FileUuid            string         `json:"file_uuid"`
	Filename            string         `json:"filename"`
	ContentType         string         `json:"content_type"`
	OwnerID             string         `json:"owner_id"`
	BucketID            string         `json:"bucket_id"`
	CreatedAt           string         `json:"created_at"`
	UpdatedAt           string         `json:"updated_at"`
	Status              string         `json:"status"`
	RetentionPeriod     sql.NullInt64  `json:"retention_period"`
	BlobSha256          sql.NullString `json:"blob_sha256"`
	SizeBytes           sql.NullInt64  `json:"size_bytes"`
	VirtType            string         `json:"virt_type"`
	Format              string         `json:"format"`
	Vcpus               sql.NullInt64  `json:"vcpus"`
	RamMb               sql.NullInt64  `json:"ram_mb"`
	ExtraAttributesJson sql.NullString `json:"extra_attributes_json"`
}

func (q *Queries) GetVMImageWithFile(ctx context.Context, fileUuid string) (GetVMImageWithFileRow, error) {
	row := q.db.QueryRowContext(ctx, getVMImageWithFile, fileUuid)
	var i GetVMImageWithFileRow
	err := row.Scan(
		&i.FileUuid,
		&i.Filename,
		&i.ContentType,
		&i.OwnerID,
		&i.BucketID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.RetentionPeriod,
		&i.BlobSha256,
		&i.SizeBytes,
		&i.VirtType,
		&i.Format,
		&i.Vcpus,
		&i.RamMb,
		&i.ExtraAttributesJson,
	)
	return i, err
}

const listBackups = `-- name: ListBackups :many
SELECT
    f.file_uuid,
    f.filename,
    f.content_type,
    f.owner_id,
    f.bucket_id,
    f.created_at,
    f.updated_at,
    f.status,
    f.retention_period,
    f.blob_sha256,
    b.size_bytes,
    bk.source_node_id,
    bk.backup_type,
    bk.is_compressed,
    bk.is_encrypted,
    bk.parent_backup_uuid
FROM
    backups bk
    JOIN files f ON f.file_uuid = bk.file_uuid
    LEFT JOIN blobs b ON b.sha256 = f.blob_sha256
ORDER BY
    f.created_at DESC
`

type ListBackupsRow struct {
	FileUuid         string         `json:"file_uuid"`
	Filename         string         `json:"filename"`
	ContentType      string         `json:"content_type"`
	OwnerID          string         `json:"owner_id"`
	BucketID         string         `json:"bucket_id"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
	Status           string         `json:"status"`
	RetentionPeriod  sql.NullInt64  `json:"retention_period"`
	BlobSha256       sql.NullString `json:"blob_sha256"`
	SizeBytes        sql.NullInt64  `json:"size_bytes"`
	SourceNodeID     sql.NullString `json:"source_node_id"`
	BackupType       string         `json:"backup_type"`
	IsCompressed     sql.NullBool   `json:"is_compressed"`
	IsEncrypted      sql.NullBool   `json:"is_encrypted"`
	ParentBackupUuid sql.NullString `json:"parent_backup_uuid"`
}

func (q *Queries) ListBackups(ctx context.Context) ([]ListBackupsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBackups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBackupsRow{}
	for rows.Next() {
		var i ListBackupsRow
		if err := rows.Scan(
			&i.FileUuid,
			&i.Filename,
			&i.ContentType,
			&i.OwnerID,
			&i.BucketID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.RetentionPeriod,
			&i.BlobSha256,
			&i.SizeBytes,
			&i.SourceNodeID,
			&i.BackupType,
			&i.IsCompressed,
			&i.IsEncrypted,
			&i.ParentBackupUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackupsByOwner = `-- name: ListBackupsByOwner :many
SELECT
    f.file_uuid,
    f.filename,
    f.content_type,
    f.owner_id,
    f.bucket_id,
    f.created_at,
    f.updated_at,
    f.status,
    f.retention_period,
    f.blob_sha256,
    b.size_bytes,
    bk.source_node_id,
    bk.backup_type,
    bk.is_compressed,
    bk.is_encrypted,
    bk.parent_backup_uuid
FROM
    backups bk
    JOIN files f ON f.file_uuid = bk.file_uuid
    LEFT JOIN blobs b ON b.sha256 = f.blob_sha256
WHERE
    f.owner_id = ?
ORDER BY
    f.created_at DESC
`

type ListBackupsByOwnerRow struct {
	FileUuid         string         `json:"file_uuid"`
	Filename         string         `json:"filename"`
	ContentType      string         `json:"content_type"`
	OwnerID          string         `json:"owner_id"`
	BucketID         string         `json:"bucket_id"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
	Status           string         `json:"status"`
	RetentionPeriod  sql.NullInt64  `json:"retention_period"`
	BlobSha256       sql.NullString `json:"blob_sha256"`
	SizeBytes        sql.NullInt64  `json:"size_bytes"`
	SourceNodeID     sql.NullString `json:"source_node_id"`
	BackupType       string         `json:"backup_type"`
	IsCompressed     sql.NullBool   `json:"is_compressed"`
	IsEncrypted      sql.NullBool   `json:"is_encrypted"`
	ParentBackupUuid sql.NullString `json:"parent_backup_uuid"`
}

func (q *Queries) ListBackupsByOwner(ctx context.Context, ownerID string) ([]ListBackupsByOwnerRow, error) {
	rows, err := q.db.QueryContext(ctx, listBackupsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBackupsByOwnerRow{}
	for rows.Next() {
		var i ListBackupsByOwnerRow
		if err := rows.Scan(
			&i.FileUuid,
			&i.Filename,
			&i.ContentType,
			&i.OwnerID,
			&i.BucketID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.RetentionPeriod,
			&i.BlobSha256,
			&i.SizeBytes,
			&i.SourceNodeID,
			&i.BackupType,
			&i.IsCompressed,
			&i.IsEncrypted,
			&i.ParentBackupUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlobsForIndex = `-- name: ListBlobsForIndex :many
SELECT
    sha256,
    file_path,
    size_bytes,
    ref_count
FROM
    blobs
`

type ListBlobsForIndexRow struct {
	Sha256    string `json:"sha256"`
	FilePath  string `json:"file_path"`
	SizeBytes int64  `json:"size_bytes"`
	RefCount  int64  `json:"ref_count"`
}

func (q *Queries) ListBlobsForIndex(ctx context.Context) ([]ListBlobsForIndexRow, error) {
	rows, err := q.db.QueryContext(ctx, listBlobsForIndex)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBlobsForIndexRow{}
	for rows.Next() {
		var i ListBlobsForIndexRow
		if err := rows.Scan(
			&i.Sha256,
			&i.FilePath,
			&i.SizeBytes,
			&i.RefCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBucketsByOwner = `-- name: ListBucketsByOwner :many
SELECT
    bucket_id,
    name,
    owner_id,
    is_public,
    required_scopes,
    created_at,
    updated_at
FROM
    buckets
WHERE
    owner_id = ?
ORDER BY
    created_at DESC
`

type ListBucketsByOwnerRow struct {
	BucketID       string         `json:"bucket_id"`
	Name           string         `json:"name"`
	OwnerID        string         `json:"owner_id"`
	IsPublic       sql.NullBool   `json:"is_public"`
	RequiredScopes sql.NullString `json:"required_scopes"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
}

func (q *Queries) ListBucketsByOwner(ctx context.Context, ownerID string) ([]ListBucketsByOwnerRow, error) {
	rows, err := q.db.QueryContext(ctx, listBucketsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBucketsByOwnerRow{}
	for rows.Next() {
		var i ListBucketsByOwnerRow
		if err := rows.Scan(
			&i.BucketID,
			&i.Name,
			&i.OwnerID,
			&i.IsPublic,
			&i.RequiredScopes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFileBlobRefs = `-- name: ListFileBlobRefs :many
SELECT
    file_uuid,
    blob_sha256,
    STATUS
FROM
    files
WHERE
    blob_sha256 IS NOT NULL
`

type ListFileBlobRefsRow struct {
	FileUuid   string         `json:"file_uuid"`
	BlobSha256 sql.NullString `json:"blob_sha256"`
	Status     string         `json:"status"`
}

func (q *Queries) ListFileBlobRefs(ctx context.Context) ([]ListFileBlobRefsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFileBlobRefs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFileBlobRefsRow{}
	for rows.Next() {
		var i ListFileBlobRefsRow
		if err := rows.Scan(&i.FileUuid, &i.BlobSha256, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFiles = `-- name: ListFiles :many
SELECT
    file_uuid,
    blob_sha256,
    filename,
    content_type,
    owner_id,
    bucket_id,
    created_at,
    updated_at,
    last_accessed_at,
    STATUS,
    retention_period
FROM
    files
ORDER BY
    created_at DESC
`

func (q *Queries) ListFiles(ctx context.Context) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.FileUuid,
			&i.BlobSha256,
			&i.Filename,
			&i.ContentType,
			&i.OwnerID,
			&i.BucketID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastAccessedAt,
			&i.Status,
			&i.RetentionPeriod,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByBucket = `-- name: ListFilesByBucket :many
SELECT
    file_uuid,
    blob_sha256,
    filename,
    content_type,
    owner_id,
    bucket_id,
    created_at,
    updated_at,
    last_accessed_at,
    STATUS,
    retention_period
FROM
    files
WHERE
    bucket_id = ?
ORDER BY
    created_at DESC
`

func (q *Queries) ListFilesByBucket(ctx context.Context, bucketID string) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listFilesByBucket, bucketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.FileUuid,
			&i.BlobSha256,
			&i.Filename,
			&i.ContentType,
			&i.OwnerID,
			&i.BucketID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastAccessedAt,
			&i.Status,
			&i.RetentionPeriod,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByBucketWithBlob = `-- name: ListFilesByBucketWithBlob :many
SELECT
    f.file_uuid,
    f.filename,
    f.content_type,
    f.owner_id,
    f.bucket_id,
    f.created_at,
    f.updated_at,
    f.last_accessed_at,
    f.status,
    f.retention_period,
    f.blob_sha256,
    b.size_bytes
FROM
    files f
    JOIN blobs b ON b.sha256 = f.blob_sha256
WHERE
    f.bucket_id = ?
ORDER BY
    f.created_at DESC
`

type ListFilesByBucketWithBlobRow struct {
	FileUuid        string         `json:"file_uuid"`
	Filename        string         `json:"filename"`
	ContentType     string         `json:"content_type"`
	OwnerID         string         `json:"owner_id"`
	BucketID        string         `json:"bucket_id"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
	LastAccessedAt  string         `json:"last_accessed_at"`
	Status          string         `json:"status"`
	RetentionPeriod sql.NullInt64  `json:"retention_period"`
	BlobSha256      sql.NullString `json:"blob_sha256"`
	SizeBytes       int64          `json:"size_bytes"`
}

func (q *Queries) ListFilesByBucketWithBlob(ctx context.Context, bucketID string) ([]ListFilesByBucketWithBlobRow, error) {
	rows, err := q.db.QueryContext(ctx, listFilesByBucketWithBlob, bucketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFilesByBucketWithBlobRow{}
	for rows.Next() {
		var i ListFilesByBucketWithBlobRow
		if err := rows.Scan(
			&i.FileUuid,
			&i.Filename,
			&i.ContentType,
			&i.OwnerID,
			&i.BucketID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastAccessedAt,
			&i.Status,
			&i.RetentionPeriod,
			&i.BlobSha256,
			&i.SizeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByOwner = `-- name: ListFilesByOwner :many
SELECT
    file_uuid,
    blob_sha256,
    filename,
    content_type,
    owner_id,
    bucket_id,
    created_at,
    updated_at,
    last_accessed_at,
    STATUS,
    retention_period
FROM
    files
WHERE
    owner_id = ?
ORDER BY
    created_at DESC
`

func (q *Queries) ListFilesByOwner(ctx context.Context, ownerID string) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listFilesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.FileUuid,
			&i.BlobSha256,
			&i.Filename,
			&i.ContentType,
			&i.OwnerID,
			&i.BucketID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastAccessedAt,
			&i.Status,
			&i.RetentionPeriod,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectFiles = `-- name: ListProjectFiles :many
SELECT
    f.file_uuid,
    f.filename,
    f.content_type,
    f.owner_id,
    f.bucket_id,
    f.created_at,
    f.updated_at,
    f.status,
    f.retention_period,
    f.blob_sha256,
    b.size_bytes,
    pf.project_id,
    pf.project_name,
    pf.version_tag,
    pf.is_read_only,
    pf.include_snapshots,
    pf.include_images,
    pf.reset_mac_addresses,
    pf.keep_compute_ids,
    pf.compression
FROM
    project_files pf
    JOIN files f ON f.file_uuid = pf.file_uuid
    LEFT JOIN blobs b ON b.sha256 = f.blob_sha256
ORDER BY
    f.created_at DESC
`

type ListProjectFilesRow struct {
	FileUuid          string         `json:"file_uuid"`
	Filename          string         `json:"filename"`
	ContentType       string         `json:"content_type"`
	OwnerID           string         `json:"owner_id"`
	BucketID          string         `json:"bucket_id"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
	Status            string         `json:"status"`
	RetentionPeriod   sql.NullInt64  `json:"retention_period"`
	BlobSha256        sql.NullString `json:"blob_sha256"`
	SizeBytes         sql.NullInt64  `json:"size_bytes"`
	ProjectID         string         `json:"project_id"`
	ProjectName       sql.NullString `json:"project_name"`
	VersionTag        sql.NullString `json:"version_tag"`
	IsReadOnly        sql.NullBool   `json:"is_read_only"`
	IncludeSnapshots  bool           `json:"include_snapshots"`
	IncludeImages     bool           `json:"include_images"`
	ResetMacAddresses bool           `json:"reset_mac_addresses"`
	KeepComputeIds    bool           `json:"keep_compute_ids"`
	Compression       string         `json:"compression"`
}

func (q *Queries) ListProjectFiles(ctx context.Context) ([]ListProjectFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectFilesRow{}
	for rows.Next() {
		var i ListProjectFilesRow
		if err := rows.Scan(
			&i.FileUuid,
			&i.Filename,
			&i.ContentType,
			&i.OwnerID,
			&i.BucketID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.RetentionPeriod,
			&i.BlobSha256,
			&i.SizeBytes,
			&i.ProjectID,
			&i.ProjectName,
			&i.VersionTag,
			&i.IsReadOnly,
			&i.IncludeSnapshots,
			&i.IncludeImages,
			&i.ResetMacAddresses,
			&i.KeepComputeIds,
			&i.Compression,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectFilesByOwner = `-- name: ListProjectFilesByOwner :many
SELECT
    f.file_uuid,
    f.filename,
    f.content_type,
    f.owner_id,
    f.bucket_id,
    f.created_at,
    f.updated_at,
    f.status,
    f.retention_period,
    f.blob_sha256,
    b.size_bytes,
    pf.project_id,
    pf.project_name,
    pf.version_tag,
    pf.is_read_only,
    pf.include_snapshots,
    pf.include_images,
    pf.reset_mac_addresses,
    pf.keep_compute_ids,
    pf.compression
FROM
    project_files pf
    JOIN files f ON f.file_uuid = pf.file_uuid
    LEFT JOIN blobs b ON b.sha256 = f.blob_sha256
WHERE
    f.owner_id = ?
ORDER BY
    f.created_at DESC
`

type ListProjectFilesByOwnerRow struct {
	FileUuid          string         `json:"file_uuid"`
	Filename          string         `json:"filename"`
	ContentType       string         `json:"content_type"`
	OwnerID           string         `json:"owner_id"`
	BucketID          string         `json:"bucket_id"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
	Status            string         `json:"status"`
	RetentionPeriod   sql.NullInt64  `json:"retention_period"`
	BlobSha256        sql.NullString `json:"blob_sha256"`
	SizeBytes         sql.NullInt64  `json:"size_bytes"`
	ProjectID         string         `json:"project_id"`
	ProjectName       sql.NullString `json:"project_name"`
	VersionTag        sql.NullString `json:"version_tag"`
	IsReadOnly        sql.NullBool   `json:"is_read_only"`
	IncludeSnapshots  bool           `json:"include_snapshots"`
	IncludeImages     bool           `json:"include_images"`
	ResetMacAddresses bool           `json:"reset_mac_addresses"`
	KeepComputeIds    bool           `json:"keep_compute_ids"`
	Compression       string         `json:"compression"`
}

func (q *Queries) ListProjectFilesByOwner(ctx context.Context, ownerID string) ([]ListProjectFilesByOwnerRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectFilesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectFilesByOwnerRow{}
	for rows.Next() {
		var i ListProjectFilesByOwnerRow
		if err := rows.Scan(
			&i.FileUuid,
			&i.Filename,
			&i.ContentType,
			&i.OwnerID,
			&i.BucketID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.RetentionPeriod,
			&i.BlobSha256,
			&i.SizeBytes,
			&i.ProjectID,
			&i.ProjectName,
			&i.VersionTag,
			&i.IsReadOnly,
			&i.IncludeSnapshots,
			&i.IncludeImages,
			&i.ResetMacAddresses,
			&i.KeepComputeIds,
			&i.Compression,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectFilesByProject = `-- name: ListProjectFilesByProject :many
SELECT
    f.file_uuid,
    f.filename,
    f.content_type,
    f.owner_id,
    f.bucket_id,
    f.created_at,
    f.updated_at,
    f.status,
    f.retention_period,
    f.blob_sha256,
    b.size_bytes,
    pf.project_id,
    pf.project_name,
    pf.version_tag,
    pf.is_read_only,
    pf.include_snapshots,
    pf.include_images,
    pf.reset_mac_addresses,
    pf.keep_compute_ids,
    pf.compression
FROM
    project_files pf
    JOIN files f ON f.file_uuid = pf.file_uuid
    LEFT JOIN blobs b ON b.sha256 = f.blob_sha256
WHERE
    pf.project_id = ?
ORDER BY
    f.created_at DESC
`

type ListProjectFilesByProjectRow struct {
	FileUuid          string         `json:"file_uuid"`
	Filename          string         `json:"filename"`
	ContentType       string         `json:"content_type"`
	OwnerID           string         `json:"owner_id"`
	BucketID          string         `json:"bucket_id"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
	Status            string         `json:"status"`
	RetentionPeriod   sql.NullInt64  `json:"retention_period"`
	BlobSha256        sql.NullString `json:"blob_sha256"`
	SizeBytes         sql.NullInt64  `json:"size_bytes"`
	ProjectID         string         `json:"project_id"`
	ProjectName       sql.NullString `json:"project_name"`
	VersionTag        sql.NullString `json:"version_tag"`
	IsReadOnly        sql.NullBool   `json:"is_read_only"`
	IncludeSnapshots  bool           `json:"include_snapshots"`
	IncludeImages     bool           `json:"include_images"`
	ResetMacAddresses bool           `json:"reset_mac_addresses"`
	KeepComputeIds    bool           `json:"keep_compute_ids"`
	Compression       string         `json:"compression"`
}

func (q *Queries) ListProjectFilesByProject(ctx context.Context, projectID string) ([]ListProjectFilesByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectFilesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectFilesByProjectRow{}
	for rows.Next() {
		var i ListProjectFilesByProjectRow
		if err := rows.Scan(
			&i.FileUuid,
			&i.Filename,
			&i.ContentType,
			&i.OwnerID,
			&i.BucketID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.RetentionPeriod,
			&i.BlobSha256,
			&i.SizeBytes,
			&i.ProjectID,
			&i.ProjectName,
			&i.VersionTag,
			&i.IsReadOnly,
			&i.IncludeSnapshots,
			&i.IncludeImages,
			&i.ResetMacAddresses,
			&i.KeepComputeIds,
			&i.Compression,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTmpUploadStatuses = `-- name: ListTmpUploadStatuses :many
SELECT
    file_uuid,
    STATUS
FROM
    files
WHERE
    STATUS IN ('pending', 'uploading')
`

type ListTmpUploadStatusesRow struct {
	FileUuid string `json:"file_uuid"`
	Status   string `json:"status"`
}

func (q *Queries) ListTmpUploadStatuses(ctx context.Context) ([]ListTmpUploadStatusesRow, error) {
	rows, err := q.db.QueryContext(ctx, listTmpUploadStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTmpUploadStatusesRow{}
	for rows.Next() {
		var i ListTmpUploadStatusesRow
		if err := rows.Scan(&i.FileUuid, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVMImages = `-- name: ListVMImages :many
SELECT
    f.file_uuid,
    f.filename,
    f.content_type,
    f.owner_id,
    f.bucket_id,
    f.created_at,
    f.updated_at,
    f.status,
    f.retention_period,
    f.blob_sha256,
    b.size_bytes,
    v.virt_type,
    v.format,
    v.vcpus,
    v.ram_mb,
    v.extra_attributes_json
FROM
    vm_images v
    JOIN files f ON f.file_uuid = v.file_uuid
    LEFT JOIN blobs b ON b.sha256 = f.blob_sha256
ORDER BY
    f.created_at DESC
`

type ListVMImagesRow struct {
	FileUuid            string         `json:"file_uuid"`
	Filename            string         `json:"filename"`
	ContentType         string         `json:"content_type"`
	OwnerID             string         `json:"owner_id"`
	BucketID            string         `json:"bucket_id"`
	CreatedAt           string         `json:"created_at"`
	UpdatedAt           string         `json:"updated_at"`
	Status              string         `json:"status"`
	RetentionPeriod     sql.NullInt64  `json:"retention_period"`
	BlobSha256          sql.NullString `json:"blob_sha256"`
	SizeBytes           sql.NullInt64  `json:"size_bytes"`
	VirtType            string         `json:"virt_type"`
	Format              string         `json:"format"`
	Vcpus               sql.NullInt64  `json:"vcpus"`
	RamMb               sql.NullInt64  `json:"ram_mb"`
	ExtraAttributesJson sql.NullString `json:"extra_attributes_json"`
}

func (q *Queries) ListVMImages(ctx context.Context) ([]ListVMImagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listVMImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVMImagesRow{}
	for rows.Next() {
		var i ListVMImagesRow
		if err := rows.Scan(
			&i.FileUuid,
			&i.Filename,
			&i.ContentType,
			&i.OwnerID,
			&i.BucketID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.RetentionPeriod,
			&i.BlobSha256,
			&i.SizeBytes,
			&i.VirtType,
			&i.Format,
			&i.Vcpus,
			&i.RamMb,
			&i.ExtraAttributesJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVMImagesByOwner = `-- name: ListVMImagesByOwner :many
SELECT
    f.file_uuid,
    f.filename,
    f.content_type,
    f.owner_id,
    f.bucket_id,
    f.created_at,
    f.updated_at,
    f.status,
    f.retention_period,
    f.blob_sha256,
    b.size_bytes,
    v.virt_type,
    v.format,
    v.vcpus,
    v.ram_mb,
    v.extra_attributes_json
FROM
    vm_images v
    JOIN files f ON f.file_uuid = v.file_uuid
    LEFT JOIN blobs b ON b.sha256 = f.blob_sha256
WHERE
    f.owner_id = ?
ORDER BY
    f.created_at DESC
`

type ListVMImagesByOwnerRow struct {
	FileUuid            string         `json:"file_uuid"`
	Filename            string         `json:"filename"`
	ContentType         string         `json:"content_type"`
	OwnerID             string         `json:"owner_id"`
	BucketID            string         `json:"bucket_id"`
	CreatedAt           string         `json:"created_at"`
	UpdatedAt           string         `json:"updated_at"`
	Status              string         `json:"status"`
	RetentionPeriod     sql.NullInt64  `json:"retention_period"`
	BlobSha256          sql.NullString `json:"blob_sha256"`
	SizeBytes           sql.NullInt64  `json:"size_bytes"`
	VirtType            string         `json:"virt_type"`
	Format              string         `json:"format"`
	Vcpus               sql.NullInt64  `json:"vcpus"`
	RamMb               sql.NullInt64  `json:"ram_mb"`
	ExtraAttributesJson sql.NullString `json:"extra_attributes_json"`
}

func (q *Queries) ListVMImagesByOwner(ctx context.Context, ownerID string) ([]ListVMImagesByOwnerRow, error) {
	rows, err := q.db.QueryContext(ctx, listVMImagesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVMImagesByOwnerRow{}
	for rows.Next() {
		var i ListVMImagesByOwnerRow
		if err := rows.Scan(
			&i.FileUuid,
			&i.Filename,
			&i.ContentType,
			&i.OwnerID,
			&i.BucketID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.RetentionPeriod,
			&i.BlobSha256,
			&i.SizeBytes,
			&i.VirtType,
			&i.Format,
			&i.Vcpus,
			&i.RamMb,
			&i.ExtraAttributesJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
