// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: selects.sql

package sqlc_file_store

import (
	"context"
	"database/sql"
)

const getFileWithVMData = `-- name: GetFileWithVMData :one
SELECT
    f.file_uuid, f.file_path, f.filename, f.size_bytes, f.checksum_sha256, f.content_type, f.scope_label, f.owner_id, f.created_at, f.updated_at, f.last_accessed_at, f.status, f.retention_period,
    v.virt_type,
    v.format,
    v.vcpus,
    v.ram_mb,
    v.extra_attributes_json
FROM
    files f
    LEFT JOIN vm_images v ON f.file_uuid = v.file_uuid
WHERE
    f.file_uuid = ?
LIMIT
    1
`

type GetFileWithVMDataRow struct {
	FileUuid            string
	FilePath            string
	Filename            string
	SizeBytes           int64
	ChecksumSha256      string
	ContentType         string
	ScopeLabel          string
	OwnerID             string
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
	LastAccessedAt      sql.NullTime
	Status              sql.NullString
	RetentionPeriod     sql.NullInt64
	VirtType            sql.NullString
	Format              sql.NullString
	Vcpus               sql.NullInt64
	RamMb               sql.NullInt64
	ExtraAttributesJson sql.NullString
}

func (q *Queries) GetFileWithVMData(ctx context.Context, fileUuid string) (GetFileWithVMDataRow, error) {
	row := q.db.QueryRowContext(ctx, getFileWithVMData, fileUuid)
	var i GetFileWithVMDataRow
	err := row.Scan(
		&i.FileUuid,
		&i.FilePath,
		&i.Filename,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.ContentType,
		&i.ScopeLabel,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAccessedAt,
		&i.Status,
		&i.RetentionPeriod,
		&i.VirtType,
		&i.Format,
		&i.Vcpus,
		&i.RamMb,
		&i.ExtraAttributesJson,
	)
	return i, err
}

const listFilesByScope = `-- name: ListFilesByScope :many
SELECT
    file_uuid, file_path, filename, size_bytes, checksum_sha256, content_type, scope_label, owner_id, created_at, updated_at, last_accessed_at, status, retention_period
FROM
    files
WHERE
    scope_label = ?
    AND STATUS = 'available'
ORDER BY
    created_at DESC
`

func (q *Queries) ListFilesByScope(ctx context.Context, scopeLabel string) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listFilesByScope, scopeLabel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.FileUuid,
			&i.FilePath,
			&i.Filename,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.ContentType,
			&i.ScopeLabel,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastAccessedAt,
			&i.Status,
			&i.RetentionPeriod,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
