// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: updates.sql

package sqlc_file_store

import (
	"context"
	"database/sql"
)

const decrementBlobRefCount = `-- name: DecrementBlobRefCount :exec
UPDATE
    blobs
SET
    ref_count = ref_count - 1,
    updated_at = CURRENT_TIMESTAMP
WHERE
    sha256 = ?
`

func (q *Queries) DecrementBlobRefCount(ctx context.Context, sha256 string) error {
	_, err := q.db.ExecContext(ctx, decrementBlobRefCount, sha256)
	return err
}

const finalizeFile = `-- name: FinalizeFile :one
UPDATE
    files
SET
    blob_sha256 = ?,
    STATUS = 'available',
    updated_at = CURRENT_TIMESTAMP
WHERE
    file_uuid = ?
RETURNING
    file_uuid, blob_sha256, filename, content_type, owner_id, bucket_id, created_at, updated_at, last_accessed_at, status, retention_period
`

type FinalizeFileParams struct {
	BlobSha256 sql.NullString `json:"blob_sha256"`
	FileUuid   string         `json:"file_uuid"`
}

func (q *Queries) FinalizeFile(ctx context.Context, arg FinalizeFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, finalizeFile, arg.BlobSha256, arg.FileUuid)
	var i File
	err := row.Scan(
		&i.FileUuid,
		&i.BlobSha256,
		&i.Filename,
		&i.ContentType,
		&i.OwnerID,
		&i.BucketID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAccessedAt,
		&i.Status,
		&i.RetentionPeriod,
	)
	return i, err
}

const incrementBlobRefCount = `-- name: IncrementBlobRefCount :exec
UPDATE
    blobs
SET
    ref_count = ref_count + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE
    sha256 = ?
`

func (q *Queries) IncrementBlobRefCount(ctx context.Context, sha256 string) error {
	_, err := q.db.ExecContext(ctx, incrementBlobRefCount, sha256)
	return err
}

const incrementTokenAccessCount = `-- name: IncrementTokenAccessCount :exec
UPDATE
    public_file_tokens
SET
    access_count = access_count + 1
WHERE
    token = ?
`

func (q *Queries) IncrementTokenAccessCount(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, incrementTokenAccessCount, token)
	return err
}

const markFileTombstoned = `-- name: MarkFileTombstoned :exec
UPDATE
    files
SET
    STATUS = 'tombstoned',
    updated_at = CURRENT_TIMESTAMP
WHERE
    file_uuid = ?
`

func (q *Queries) MarkFileTombstoned(ctx context.Context, fileUuid string) error {
	_, err := q.db.ExecContext(ctx, markFileTombstoned, fileUuid)
	return err
}

const updateBucket = `-- name: UpdateBucket :exec
UPDATE
    buckets
SET
    name = ?,
    is_public = ?,
    required_scopes = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE
    bucket_id = ?
`

type UpdateBucketParams struct {
	Name           string         `json:"name"`
	IsPublic       sql.NullBool   `json:"is_public"`
	RequiredScopes sql.NullString `json:"required_scopes"`
	BucketID       string         `json:"bucket_id"`
}

func (q *Queries) UpdateBucket(ctx context.Context, arg UpdateBucketParams) error {
	_, err := q.db.ExecContext(ctx, updateBucket,
		arg.Name,
		arg.IsPublic,
		arg.RequiredScopes,
		arg.BucketID,
	)
	return err
}

const updateFileBucket = `-- name: UpdateFileBucket :exec
UPDATE
    files
SET
    bucket_id = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE
    file_uuid = ?
`

type UpdateFileBucketParams struct {
	BucketID string `json:"bucket_id"`
	FileUuid string `json:"file_uuid"`
}

func (q *Queries) UpdateFileBucket(ctx context.Context, arg UpdateFileBucketParams) error {
	_, err := q.db.ExecContext(ctx, updateFileBucket, arg.BucketID, arg.FileUuid)
	return err
}

const updateFileLastAccessedAt = `-- name: UpdateFileLastAccessedAt :exec
UPDATE
    files
SET
    last_accessed_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE
    file_uuid = ?
`

func (q *Queries) UpdateFileLastAccessedAt(ctx context.Context, fileUuid string) error {
	_, err := q.db.ExecContext(ctx, updateFileLastAccessedAt, fileUuid)
	return err
}

const updateFileMetadata = `-- name: UpdateFileMetadata :exec
UPDATE
    files
SET
    filename = ?,
    content_type = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE
    file_uuid = ?
`

type UpdateFileMetadataParams struct {
	Filename    string `json:"filename"`
	ContentType string `json:"content_type"`
	FileUuid    string `json:"file_uuid"`
}

func (q *Queries) UpdateFileMetadata(ctx context.Context, arg UpdateFileMetadataParams) error {
	_, err := q.db.ExecContext(ctx, updateFileMetadata, arg.Filename, arg.ContentType, arg.FileUuid)
	return err
}

const updateFileStatus = `-- name: UpdateFileStatus :exec
UPDATE
    files
SET
    STATUS = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE
    file_uuid = ?
`

type UpdateFileStatusParams struct {
	Status   string `json:"status"`
	FileUuid string `json:"file_uuid"`
}

func (q *Queries) UpdateFileStatus(ctx context.Context, arg UpdateFileStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateFileStatus, arg.Status, arg.FileUuid)
	return err
}
