// Code generated by protoc-gen-go-drpc. DO NOT EDIT.
// protoc-gen-go-drpc version: v0.0.34
// source: master.proto

package master

import (
	context "context"
	errors "errors"
	protojson "google.golang.org/protobuf/encoding/protojson"
	proto "google.golang.org/protobuf/proto"
	drpc "storj.io/drpc"
	drpcerr "storj.io/drpc/drpcerr"
)

type drpcEncoding_File_master_proto struct{}

func (drpcEncoding_File_master_proto) Marshal(msg drpc.Message) ([]byte, error) {
	return proto.Marshal(msg.(proto.Message))
}

func (drpcEncoding_File_master_proto) MarshalAppend(buf []byte, msg drpc.Message) ([]byte, error) {
	return proto.MarshalOptions{}.MarshalAppend(buf, msg.(proto.Message))
}

func (drpcEncoding_File_master_proto) Unmarshal(buf []byte, msg drpc.Message) error {
	return proto.Unmarshal(buf, msg.(proto.Message))
}

func (drpcEncoding_File_master_proto) JSONMarshal(msg drpc.Message) ([]byte, error) {
	return protojson.Marshal(msg.(proto.Message))
}

func (drpcEncoding_File_master_proto) JSONUnmarshal(buf []byte, msg drpc.Message) error {
	return protojson.Unmarshal(buf, msg.(proto.Message))
}

type DRPCMasterSyncServiceClient interface {
	DRPCConn() drpc.Conn

	CheckPermission(ctx context.Context, in *CheckPermissionRequest) (*CheckPermissionResponse, error)
	RegisterJob(ctx context.Context, in *RegisterJobRequest) (*RegisterJobResponse, error)
}

type drpcMasterSyncServiceClient struct {
	cc drpc.Conn
}

func NewDRPCMasterSyncServiceClient(cc drpc.Conn) DRPCMasterSyncServiceClient {
	return &drpcMasterSyncServiceClient{cc}
}

func (c *drpcMasterSyncServiceClient) DRPCConn() drpc.Conn { return c.cc }

func (c *drpcMasterSyncServiceClient) CheckPermission(ctx context.Context, in *CheckPermissionRequest) (*CheckPermissionResponse, error) {
	out := new(CheckPermissionResponse)
	err := c.cc.Invoke(ctx, "/master.MasterSyncService/CheckPermission", drpcEncoding_File_master_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcMasterSyncServiceClient) RegisterJob(ctx context.Context, in *RegisterJobRequest) (*RegisterJobResponse, error) {
	out := new(RegisterJobResponse)
	err := c.cc.Invoke(ctx, "/master.MasterSyncService/RegisterJob", drpcEncoding_File_master_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type DRPCMasterSyncServiceServer interface {
	CheckPermission(context.Context, *CheckPermissionRequest) (*CheckPermissionResponse, error)
	RegisterJob(context.Context, *RegisterJobRequest) (*RegisterJobResponse, error)
}

type DRPCMasterSyncServiceUnimplementedServer struct{}

func (s *DRPCMasterSyncServiceUnimplementedServer) CheckPermission(context.Context, *CheckPermissionRequest) (*CheckPermissionResponse, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCMasterSyncServiceUnimplementedServer) RegisterJob(context.Context, *RegisterJobRequest) (*RegisterJobResponse, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

type DRPCMasterSyncServiceDescription struct{}

func (DRPCMasterSyncServiceDescription) NumMethods() int { return 2 }

func (DRPCMasterSyncServiceDescription) Method(n int) (string, drpc.Encoding, drpc.Receiver, interface{}, bool) {
	switch n {
	case 0:
		return "/master.MasterSyncService/CheckPermission", drpcEncoding_File_master_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCMasterSyncServiceServer).
					CheckPermission(
						ctx,
						in1.(*CheckPermissionRequest),
					)
			}, DRPCMasterSyncServiceServer.CheckPermission, true
	case 1:
		return "/master.MasterSyncService/RegisterJob", drpcEncoding_File_master_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCMasterSyncServiceServer).
					RegisterJob(
						ctx,
						in1.(*RegisterJobRequest),
					)
			}, DRPCMasterSyncServiceServer.RegisterJob, true
	default:
		return "", nil, nil, nil, false
	}
}

func DRPCRegisterMasterSyncService(mux drpc.Mux, impl DRPCMasterSyncServiceServer) error {
	return mux.Register(impl, DRPCMasterSyncServiceDescription{})
}

type DRPCMasterSyncService_CheckPermissionStream interface {
	drpc.Stream
	SendAndClose(*CheckPermissionResponse) error
}

type drpcMasterSyncService_CheckPermissionStream struct {
	drpc.Stream
}

func (x *drpcMasterSyncService_CheckPermissionStream) SendAndClose(m *CheckPermissionResponse) error {
	if err := x.MsgSend(m, drpcEncoding_File_master_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCMasterSyncService_RegisterJobStream interface {
	drpc.Stream
	SendAndClose(*RegisterJobResponse) error
}

type drpcMasterSyncService_RegisterJobStream struct {
	drpc.Stream
}

func (x *drpcMasterSyncService_RegisterJobStream) SendAndClose(m *RegisterJobResponse) error {
	if err := x.MsgSend(m, drpcEncoding_File_master_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}
