// Code generated by protoc-gen-go-drpc. DO NOT EDIT.
// protoc-gen-go-drpc version: v0.0.34
// source: master.proto

package master

import (
	context "context"
	errors "errors"

	protojson "google.golang.org/protobuf/encoding/protojson"
	proto "google.golang.org/protobuf/proto"
	drpc "storj.io/drpc"
	drpcerr "storj.io/drpc/drpcerr"
)

type drpcEncoding_File_master_proto struct{}

func (drpcEncoding_File_master_proto) Marshal(msg drpc.Message) ([]byte, error) {
	return proto.Marshal(msg.(proto.Message))
}

func (drpcEncoding_File_master_proto) MarshalAppend(buf []byte, msg drpc.Message) ([]byte, error) {
	return proto.MarshalOptions{}.MarshalAppend(buf, msg.(proto.Message))
}

func (drpcEncoding_File_master_proto) Unmarshal(buf []byte, msg drpc.Message) error {
	return proto.Unmarshal(buf, msg.(proto.Message))
}

func (drpcEncoding_File_master_proto) JSONMarshal(msg drpc.Message) ([]byte, error) {
	return protojson.Marshal(msg.(proto.Message))
}

func (drpcEncoding_File_master_proto) JSONUnmarshal(buf []byte, msg drpc.Message) error {
	return protojson.Unmarshal(buf, msg.(proto.Message))
}

type DRPCMasterSyncServiceClient interface {
	DRPCConn() drpc.Conn

	FullSync(ctx context.Context, in *FullSyncRequest) (*FullSyncResponse, error)
}

type drpcMasterSyncServiceClient struct {
	cc drpc.Conn
}

func NewDRPCMasterSyncServiceClient(cc drpc.Conn) DRPCMasterSyncServiceClient {
	return &drpcMasterSyncServiceClient{cc}
}

func (c *drpcMasterSyncServiceClient) DRPCConn() drpc.Conn { return c.cc }

func (c *drpcMasterSyncServiceClient) FullSync(ctx context.Context, in *FullSyncRequest) (*FullSyncResponse, error) {
	out := new(FullSyncResponse)
	err := c.cc.Invoke(ctx, "/master.MasterSyncService/FullSync", drpcEncoding_File_master_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type DRPCMasterSyncServiceServer interface {
	FullSync(context.Context, *FullSyncRequest) (*FullSyncResponse, error)
}

type DRPCMasterSyncServiceUnimplementedServer struct{}

func (s *DRPCMasterSyncServiceUnimplementedServer) FullSync(context.Context, *FullSyncRequest) (*FullSyncResponse, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

type DRPCMasterSyncServiceDescription struct{}

func (DRPCMasterSyncServiceDescription) NumMethods() int { return 1 }

func (DRPCMasterSyncServiceDescription) Method(n int) (string, drpc.Encoding, drpc.Receiver, interface{}, bool) {
	switch n {
	case 0:
		return "/master.MasterSyncService/FullSync", drpcEncoding_File_master_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCMasterSyncServiceServer).
					FullSync(
						ctx,
						in1.(*FullSyncRequest),
					)
			}, DRPCMasterSyncServiceServer.FullSync, true
	default:
		return "", nil, nil, nil, false
	}
}

func DRPCRegisterMasterSyncService(mux drpc.Mux, impl DRPCMasterSyncServiceServer) error {
	return mux.Register(impl, DRPCMasterSyncServiceDescription{})
}

type DRPCMasterSyncService_FullSyncStream interface {
	drpc.Stream
	SendAndClose(*FullSyncResponse) error
}

type drpcMasterSyncService_FullSyncStream struct {
	drpc.Stream
}

func (x *drpcMasterSyncService_FullSyncStream) SendAndClose(m *FullSyncResponse) error {
	if err := x.MsgSend(m, drpcEncoding_File_master_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}
