DROP TABLE IF EXISTS project_files;

DROP TABLE IF EXISTS backups;

DROP TABLE IF EXISTS vm_images;

DROP TABLE IF EXISTS files;

DROP TABLE IF EXISTS buckets;

DROP TABLE IF EXISTS public_file_tokens;

DROP TABLE IF EXISTS blobs;
