syntax = "proto3";
package master;

import "shared.proto";

option go_package = "github.com/0xveya/gns3util/internal/shared/pb/master";

message CheckPermissionRequest {
  string user_id = 1;
  string jti = 2;
  repeated string role_names = 3;
  shared.Action required_action = 4;
  shared.Resource required_resource = 5;
}

message CheckPermissionResponse {
  bool allowed = 1;
}

message RegisterJobRequest {
  string job_name = 1;
  string node_id = 2;
  string interval = 3;
  string description = 4;
}

message RegisterJobResponse {
  bool success = 1;
}

service MasterSyncService {
  rpc CheckPermission(CheckPermissionRequest) returns (CheckPermissionResponse);
  rpc RegisterJob(RegisterJobRequest) returns (RegisterJobResponse);
}
